/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.86
 * Generated at: 2018-05-01 04:58:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane.SystemMenuBar;
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;
import javax.script.*;
import java.nio.file.*;
import java.nio.charset.*;
import java.text.DateFormat;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import org.apache.taglibs.standard.tag.common.sql.ResultImpl;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.lang.Integer;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;

public final class addmorepackage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Admin/included/NewHeader.jsp", Long.valueOf(1524567356000L));
    _jspx_dependants.put("/WEB-INF/sessionCheck1.jspf", Long.valueOf(1524567358000L));
    _jspx_dependants.put("/Admin/included/Newfooter.jsp", Long.valueOf(1524567356000L));
    _jspx_dependants.put("/Admin/sessionCheck.jsp", Long.valueOf(1524567356000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fdataSource;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.release();
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fdataSource.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
int timeout = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout + "; URL = admn_login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/form-style.css\">\r\n");
      out.write("\t\t");

 String theme3 = (String) pageContext.getAttribute("myTheme", PageContext.SESSION_SCOPE);
if (theme3!=null) {
if (theme3.equalsIgnoreCase("brown") ) { 
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
 } else if (theme3.equalsIgnoreCase("blue")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBlue.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("green")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmGreen.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("magenta")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/Thmmagenta.css\">\r\n");
      out.write("\t\t");
}
} else {
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>PDAMS</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".white-marquee {\r\n");
      out.write("   font-family:   arial, serif, \"Times New Roman\", calibri, Times;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor:  white;\r\n");
      out.write("\t//margin-left:50px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tpadding-bottom:5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");

//String mailstatus=(String)session.getAttribute("MailStatus"); 
//String user = (String) session.getAttribute("user_name");
String user_code = (String) session.getAttribute("User_Code");
if (user_code!=null) {} else {user_code="0";}
 String mq=null, mqLaunch=null, mqMaint=null, mqOther=null, mqRly=null, mqRVNL=null;					
 //System.out.println("code="+user_code);	
  Connection conn7 = null;
     			PreparedStatement ps777=null;
     			ResultSet  rs777=null;
     						//Statement stmt7 = null;
     						try {
     							Context initCtx = new InitialContext();
     							Context envCtx = (Context) initCtx.lookup("java:comp/env");
     							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");

     							conn7 = ds.getConnection();
     							String sql35 = "select item, description from xx_maintenance";
     									
    								ps777 = conn7.prepareStatement(sql35);
    								rs777 = ps777.executeQuery();
    								while (rs777.next()) {
    									String item=rs777.getString(1);
    									 String desc=rs777.getString(2);
    									if (item.equalsIgnoreCase("marquee-launch")) {
    										mqLaunch=desc;
    									} else if (item.equalsIgnoreCase("marquee-maint")) {
    										mqMaint=desc;
    									} else if (item.equalsIgnoreCase("marquee-other")) {
    										mqOther=desc;
    									} else if (item.equalsIgnoreCase("marquee-Rly")) {
    										mqRly=desc;
    									} else if (item.equalsIgnoreCase("marquee-RVNL")) {
    										mqRVNL=desc;
    									} 
    								}
    								if (user_code.equalsIgnoreCase("2")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRly;
    								} else if (user_code.equalsIgnoreCase("5")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRVNL;
    								} else {
    								mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther;
    								}		 
    				    				//System.out.println("marquee="+mq);
     						}catch(Exception e){
    							
    							e.printStackTrace();
    						} finally {
    						    try { rs777.close(); } catch (Exception e) { /* ignored */ }
    						    try { ps777.close(); } catch (Exception e) { /* ignored */ }
    						    try { conn7.close(); } catch (Exception e) { /* ignored */ }
    						}



      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"menu1\" value='");
      out.print(session.getAttribute("user_name") );
      out.write("'>\r\n");
      out.write("     \t   <div class=\"header\">\r\n");
      out.write("   \r\n");
      out.write(" \t\t   <table width=\"100%\"><tr><th width=15%>\r\n");
      out.write("    \t\t  <img src=\"images/Rail_logo.png\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write("    \t\t  \r\n");
      out.write("   </td>\r\n");
      out.write("   <th width=60%>\r\n");
      out.write("      \t\t <h2 style=\" margin-left:5px;\"><i>Project Documents Approval Monitoring System (PDAMS)</i></h2>\t\r\n");
      out.write("   \r\n");
      out.write("   </th><th width=25%>\r\n");
      out.write("\t  <img src=\"images/RVNL_LOGO.jpg\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write(" \t\t  </table>\t\r\n");
      out.write("   </div>\r\n");
      out.write("\t   <div class=\"topmenu\" id=\"menu\">\r\n");
      out.write("\t  <div id=\"menu1\"  style=\"float:left;\"> \r\n");
      out.write("\t  \t\t<ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<!-- <li><a href=\"user_index.jsp\">Add/Modify Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"user_Project.jsp\">My Projects</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"Reportpiuinitiate.jsp\">My Reports</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"MoreInfo.jsp\">Returned Tasks</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"PullBack.jsp\">PullBack Doc</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinalApproval.jsp\">Docs under Approval</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinallyApprovedShow.jsp\">Approved Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"ManualMail.jsp\">Reminders</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"User_List.jsp\">User List</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"changepasswordlocaladmin.jsp\">Change Password</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"helpmain.jsp\">Help</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"admn_logout.jsp\">Logout</a></li>  -->\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"NewIndex.jsp\">Home</a></li>\r\n");
      out.write("\t   \t\t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t</ul>\t \r\n");
      out.write("\t   \t\t\t\t\t</div>  \r\n");
      out.write("\t   \t\t\t\t\t");

	   					if (!mq.equalsIgnoreCase("") && mq!=null) {
	   					
      out.write("\t\r\n");
      out.write("\t   \t<div id=\"menu11\" ></div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t   <div id=\"menu2\"  style=\"width:70%; float:left;\">     \t\t\t\t\t\r\n");
      out.write("\t   <marquee><span class=\"white-marquee\" id=\"white-marquee\" style=\"float:right; width:100%\">");
      out.print(mq );
      out.write("</span></marquee>  </div>\r\n");
      out.write("\t  ");

	  	}
	   	
      out.write("\t\r\n");
      out.write("\t   \t\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 

int timeout1 = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout1 + "; URL = admn_login.jsp");

if(((String)session.getAttribute("user_name"))==null)
       {
           
	response.sendRedirect("admn_login.jsp");
           
       }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"resources/JS/Approval_wf230.js\"></script>\r\n");
      out.write(" <link\r\n");
      out.write("\thref=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>RVNL Document Portal </title>\r\n");
      out.write("<link href=\"resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">    \r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<script src=\"resources/JS/backButton.js\"></script>\r\n");
      out.write("<script src=\"resources/JS/validate230.js\"></script>\r\n");
      out.write("<script src=\"resources/JS/PIU_depend230.js\"></script>\r\n");
      out.write("<script src=\"resources/jQuery/jquery-1.12.3.min.js\"></script> \r\n");
      out.write("<style>\r\n");
      out.write(".ui-datepicker-year {\r\n");
      out.write("   background-color: #cc0000;\r\n");
      out.write(" padding-left:20px;\r\n");
      out.write("}\r\n");
      out.write("textarea {\r\n");
      out.write("   resize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("* { font-family:Arial; }\r\n");
      out.write("h2 { padding:0 0 5px 5px; }\r\n");
      out.write("h2 a { color: #224f99; }\r\n");
      out.write("a { color:#999; text-decoration: none; }\r\n");
      out.write("a:hover { color:#802727; }\r\n");
      out.write("p { padding:0 0 5px 0; }\r\n");
      out.write("\r\n");
      out.write("input { padding:5px; border:1px solid #999; border-radius:4px; -moz-border-radius:4px; -web-kit-border-radius:4px; -khtml-border-radius:4px; }\r\n");
      out.write("div.absolute {\r\n");
      out.write("   \tposition:absolute;\r\n");
      out.write("   \tmargin-top: 5px;\r\n");
      out.write("   \tmargin-left: 39px;\r\n");
      out.write("   \tmargin-bottom: 20px;\r\n");
      out.write(" \tpadding: 15 px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    border: 3px double #ff4d4d;\r\n");
      out.write("    background-color:#ffe6e6;\r\n");
      out.write("        }\r\n");
      out.write("    table.center {\r\n");
      out.write("    margin-left:auto; \r\n");
      out.write("    margin-right:auto;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"resources/jQuery/jquery-ui.js\"></script>\r\n");
      out.write("<!--  <script src=\"resources/jQuery/CSS/jquery-ui.css\"></script> -->\r\n");
      out.write(" <!--  <script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("  <script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function refreshAndClose() {\r\n");
      out.write("        window.opener.location.reload(true);\r\n");
      out.write("        window.close();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("   <script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#start_Date\").datepicker({\r\n");
      out.write("\t\t\tdateFormat : 'dd/mm/yy',\r\n");
      out.write("\t\t\t\tmaxDate:'0', changeYear: true\r\n");
      out.write("\t\t}).val();\r\n");
      out.write("\t\t//  $( \"#Dateofsubmission\" ).datepicker();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\tfunction frezedate(id, startDate) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $j = jQuery.noConflict();\r\n");
      out.write("\r\n");
      out.write("\t\tvar idof = id;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* var chunks = startDate.split('-'); */\r\n");
      out.write("\t\tvar formattedDate =startDate;// [ chunks[2], chunks[1], chunks[0] ].join(\"/\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$j(\"#\" + idof).datepicker({\r\n");
      out.write("\r\n");
      out.write("\t\t\tdateFormat : 'dd/mm/yy',\r\n");
      out.write("\t\t\tminDate : formattedDate,\r\n");
      out.write("\t\t\tmaxDate : '0', changeYear: true\r\n");
      out.write("\r\n");
      out.write("\t\t}).datepicker(\"show\").val();\r\n");
      out.write("\t\t//var today = new Date(); var dd = today.getDate(); \r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function stopRKey(evt) { \r\n");
      out.write("\t  var evt = (evt) ? evt : ((event) ? event : null); \r\n");
      out.write("\t  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null); \r\n");
      out.write("\t  if ((evt.keyCode == 13) && (node.type==\"text\"))  {return false;} \r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("\tdocument.onkeypress = stopRKey; \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function loadXMLDoc(element,er)\r\n");
      out.write("{\r\n");
      out.write("var xmlhttp;\r\n");
      out.write("var k=document.getElementById(element).value;\r\n");
      out.write("var urls=\"projectexist.jsp?ver=\"+k;\r\n");
      out.write("\r\n");
      out.write("if (window.XMLHttpRequest)\r\n");
      out.write("  {\r\n");
      out.write("  xmlhttp=new XMLHttpRequest();\r\n");
      out.write("  }\r\n");
      out.write("else\r\n");
      out.write("  {\r\n");
      out.write("  xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("  }\r\n");
      out.write("xmlhttp.onreadystatechange=function()\r\n");
      out.write("  {\r\n");
      out.write("  if (xmlhttp.readyState==4)\r\n");
      out.write("    {\r\n");
      out.write("        //document.getElementById(\"err\").style.color=\"red\";\r\n");
      out.write("        document.getElementById(er).innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t\tvar ex=document.getElementById(\"exist\");\r\n");
      out.write("\t\tif(ex!=null){\r\n");
      out.write("\t\t\tdocument.getElementById(\"btnclick\").disabled = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"btnclick\").disabled = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("xmlhttp.open(\"GET\",urls,true);\r\n");
      out.write("xmlhttp.send();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showDivisionspackage(str,index) {\r\n");
      out.write("\tshowDivisionspackagesub1(str,index);\r\n");
      out.write("\tshowDivisionspackagesub2(str,index);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showDivisionspackagesub1(str1,index){\r\n");
      out.write("\tindex1=index;\r\n");
      out.write("\tvar str = encodeURIComponent(str1);\r\n");
      out.write("\t\r\n");
      out.write("\tif (typeof XMLHttpRequest != \"undefined\") {\r\n");
      out.write("\t\txmlHttp3 = new XMLHttpRequest();\r\n");
      out.write("\t} else if (window.ActiveXObject) {\r\n");
      out.write("\t\txmlHttp3 = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif (xmlHttp3 == null) {\r\n");
      out.write("\t\talert(\"Browser does not support XMLHTTP Request\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar url = \"Divisions_checkBoxPackage.jsp\";\r\n");
      out.write("\tvar z=\"Zone1\";\r\n");
      out.write("\turl += \"?cont=\" + str+\"&zone=\"+z+\"&index=\"+index+\"&id=1\";\r\n");
      out.write("\txmlHttp3.onreadystatechange = stateChangespackage;\r\n");
      out.write("\txmlHttp3.open(\"GET\", url, true);\r\n");
      out.write("\txmlHttp3.send(null);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function showDivisionspackagesub2(str1,index){\r\n");
      out.write("\tvar str = encodeURIComponent(str1);\r\n");
      out.write("\tindex1=index;\r\n");
      out.write("\tif (typeof XMLHttpRequest != \"undefined\") {\r\n");
      out.write("\t\txmlHttp2 = new XMLHttpRequest();\r\n");
      out.write("\t} else if (window.ActiveXObject) {\r\n");
      out.write("\t\txmlHttp2 = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif (xmlHttp2 == null) {\r\n");
      out.write("\t\talert(\"Browser does not support XMLHTTP Request\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar url = \"Divisions_checkBoxPackage.jsp\";\r\n");
      out.write("\tvar z=\"Zone1\";\r\n");
      out.write("\turl += \"?cont=\" + str+\"&zone=\"+z+\"&index=\"+index+\"&id=1\";\r\n");
      out.write("\txmlHttp2.onreadystatechange = stateChangespackage;  // need to be changed for another dropdown\r\n");
      out.write("\txmlHttp2.open(\"GET\", url, true);\r\n");
      out.write("\txmlHttp2.send(null);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function stateChangespackage() {\r\n");
      out.write("\tvar divid=\"state\"+index1;\r\n");
      out.write("\r\n");
      out.write("\tif (xmlHttp3.readyState == 4 || xmlHttp3.readyState == \"complete\") {\r\n");
      out.write("\t\tdocument.getElementById(divid).innerHTML = xmlHttp3.responseText\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showDivisions2package(str1,index) {\r\n");
      out.write("\tvar str = encodeURIComponent(str1);\r\n");
      out.write("\tindex2=index;\r\n");
      out.write("\tif (typeof XMLHttpRequest != \"undefined\") {\r\n");
      out.write("\t\txmlHttp3 = new XMLHttpRequest();\r\n");
      out.write("\t} else if (window.ActiveXObject) {\r\n");
      out.write("\t\txmlHttp3 = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif (xmlHttp3 == null) {\r\n");
      out.write("\t\talert(\"Browser does not support XMLHTTP Request\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (typeof XMLHttpRequest != \"undefined\") {\r\n");
      out.write("\t\txmlHttp2 = new XMLHttpRequest();\r\n");
      out.write("\t} else if (window.ActiveXObject) {\r\n");
      out.write("\t\txmlHttp2= new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif (xmlHttp2== null) {\r\n");
      out.write("\t\talert(\"Browser does not support XMLHTTP Request\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar url = \"Divisions_checkBoxPackage.jsp\";\r\n");
      out.write("\tvar z=\"Zone2\";\r\n");
      out.write("\turl += \"?cont=\" + str+\"&zone=\"+z+\"&index=\"+index+\"&id=2\";\r\n");
      out.write("\txmlHttp3.onreadystatechange = stateChanges2package;\r\n");
      out.write("\txmlHttp3.open(\"GET\", url, true);\r\n");
      out.write("\txmlHttp3.send(null);\r\n");
      out.write("//\tvar piu=document.getElementById('piuid1');\r\n");
      out.write("//\tvar url1 = \"zone2inner.jsp\";\r\n");
      out.write("//\tvar z1=\"Zonetwo\"+index;\r\n");
      out.write("//\turl1 += \"?cont=\" + piu+\"&zone=\"+z1+\"&index=\"+index+\"&id=2\";\r\n");
      out.write("//\txmlHttp2.onreadystatechange = stateChanges2package;\r\n");
      out.write("//\txmlHttp2.open(\"GET\", url1, true);\r\n");
      out.write("//\txmlHttp2.send(null);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function packnamecheck(str,packal3) {\r\n");
      out.write("\t//alert(str+\"hiiiiii\"+packal3);\r\n");
      out.write("\tif (packal3.includes(str)) {\r\n");
      out.write("\t\t\t var dialogid=\"#dialogid1\";\r\n");
      out.write("//alert(\"inside...\");\r\n");
      out.write("\t\t\t\t $(dialogid).dialog({\r\n");
      out.write("\t\t\t        modal: true,\r\n");
      out.write("\t\t\t        autoOpen: false,\r\n");
      out.write("\t\t\t        title: \"Alert Same Package Name\",\r\n");
      out.write("\t\t\t        width: 400,\r\n");
      out.write("\t\t\t        height: 200\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t document.getElementById(\"btnclick\").disabled = true;\r\n");
      out.write("\t\t  \t\t $(dialogid).dialog('open');\r\n");
      out.write("\t\t          return false;\r\n");
      out.write("\t\t       \t  \t\t\t\r\n");
      out.write("\t\t  \t\t}else{\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t  \t\t\tdocument.getElementById(\"btnclick\").disabled = false;\r\n");
      out.write("\t\t  \t\t\t\r\n");
      out.write("\t\t  \t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("function stateChanges2package() {\r\n");
      out.write("\tvar divid=\"state2\"+index2;\r\n");
      out.write("\r\n");
      out.write("\tif (xmlHttp3.readyState == 4 || xmlHttp3.readyState == \"complete\") {\r\n");
      out.write("\t\tdocument.getElementById(divid).innerHTML = xmlHttp3.responseText\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String user = (String)session.getAttribute("user_name");
//System.out.println("UZER:"+user);
String Id =request.getParameter("ID");

System.out.println("Docid="+Id);
int count1=1,i=0;

      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"project_Id\" id=\"project_Id\" value=\"");
      out.print(Id);
      out.write("\">\r\n");
      out.write("<div class=\"absolute\" style=\"font-weight:bold\" ><h8>&nbsp;&nbsp;&nbsp;[Create Project] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h8>\r\n");
      out.write("\r\n");
      out.write("<h8><font style=\"color:red; font-weight:normal\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome&nbsp;</font><font style=\"color:#3333cc; font-weight:normal\">:&nbsp;");
      out.print((String)session.getAttribute("user_name") );
      out.write("&nbsp;&nbsp;&nbsp;</font></h8>\r\n");
      out.write("</div>\r\n");
      out.write("<form name=\"CreateProject\" id=\"CreateProject\" method=\"post\" style=\"margin-left:40px;\" >\r\n");
      out.write("\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"count\">\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"ProjectID\">\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"Project_stage\">\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"document_type\">\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"designation\">\r\n");
      out.write("<INPUT TYPE=\"HIDDEN\" NAME=\"Department_RVNL\">\r\n");
      out.write("\r\n");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /Admin/addmorepackage.jsp(327,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.Project_stage == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t");

			String startdate1=request.getParameter("dateofproject");
			String projectid=request.getParameter("projectid");
			//java.util.ArrayList<String> packal3=new java.util.ArrayList<String>();
			String packal3=request.getParameter("packal3");
			//packal3 = packal4.split("~");
			String piu11=request.getParameter("PIU");
			
            out.write("\r\n");
            out.write("\t\t\t<input type=\"hidden\" name=\"projectidmain\" id=\"projectidmain\" value=\"");
            out.print(projectid);
            out.write("\">\r\n");
            out.write("\t\t\t<table style=\"background-color: #F0FFFF;width:100%;  margin-top:70px;\"\" class=\"table table-hover table-bordered\">\r\n");
            out.write("\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t\t\t<td>\r\n");
            out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Package name : </b>\r\n");
            out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"text\" name=\"Package");
            out.print(i );
            out.write("\" id =\"Package");
            out.print(i );
            out.write("\" maxlength=\"50\" onchange=\"packnamecheck(this.value,'");
            out.print(packal3);
            out.write("');\" style=\"width:204px; margin-left:15px\">\r\n");
            out.write("\t\t\t\t\t\t<br><br>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Package Start Date:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write(" \t\t\t\t<input type=\"text\" name=\"pacstart_Date");
            out.print(i);
            out.write("\" id =\"pacstart_Date");
            out.print(i);
            out.write("\" readonly=\"true\" onclick=\"frezedate('pacstart_Date");
            out.print(i);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(startdate1);
            out.write("')\" style=\"width:204px\"> <br />\r\n");
            out.write("\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t");

						Connection con =null;
						ResultSet  rs21=null,rs31=null,rs311=null,rs32=null,rs312=null,dep_rs=null, drg_rs7=null;
						
						try {
							Context initCtx = new InitialContext();
							Context envCtx = (Context) initCtx.lookup("java:comp/env");
							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");

							 con = ds.getConnection();

						
            out.write("\r\n");
            out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Railway:\r\n");
            out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<select name='Railway");
            out.print(i);
            out.write("'  class=\"drop");
            out.print(i);
            out.write("\" style=\"width:205px\" id =\"Railway");
            out.print(i);
            out.write("\" onchange=\"showDivisionspackage(this.value,");
            out.print(i);
            out.write(")\">\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"none\">--Select Zone --</option>\r\n");
            out.write("\t\t\t");

			//String piu11 =(String)pageContext.getAttribute("PIU",PageContext.SESSION_SCOPE);
			System.out.println("piu is xx "+piu11);
			Statement stmt1 = con.createStatement();
			 rs21 = stmt1.executeQuery("select PIU_Id from xx_piu_master where PIU_Name='"+piu11+"'");
			int test3=0;
			while (rs21.next()) {
				test3 = rs21.getInt("PIU_Id");
			
			}
				
					Statement stmt = con.createStatement();
					 rs311 = stmt.executeQuery("select distinct Zone_ID from xx_user_zone_mapping where piu_Id="+test3);

					while (rs311.next()) {
					String Zid = rs311.getString("Zone_ID");
					String sql31 = "select * from xx_zones_master where Zone_Id="+Zid+" order by Zone_Name";
					PreparedStatement ps31 = con.prepareStatement(sql31);
					 rs31 = ps31.executeQuery();
					while (rs31.next()) {
						String zname=rs31.getString("Zone_Name");
								
			
			
            out.write("\r\n");
            out.write("\t\t\t<option value=\"");
            out.print(zname);
            out.write('"');
            out.write('>');
            out.print(zname);
            out.write("</option>\r\n");
            out.write("\t\t\t");

				}
				}
			
            out.write("\r\n");
            out.write("\t\t\t</select> \r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t<select name='secondRailway");
            out.print(i);
            out.write("' class=\"drop");
            out.print(i);
            out.write("\" style=\"width: 205px; margin-left:50px\" id =\"secondRailway");
            out.print(i);
            out.write("\" onchange=\"showDivisions2package(this.value,");
            out.print(i);
            out.write(")\" >\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"none\">--Select Zone --</option>\r\n");
            out.write("\t\t\t");
 
			Statement stmt3=con.createStatement();
			  rs312 = stmt3.executeQuery("select distinct Zone_ID from xx_user_zone_mapping where piu_Id="+test3);
	while (rs312.next()) {
	String Zid = rs312.getString("Zone_ID");
		Statement stmt32=con.createStatement();
		 rs32 = stmt32.executeQuery("select * from xx_zones_master where Zone_Id="+Zid+" order by Zone_Name");
		while (rs32.next()) {
		String zname2 = rs32.getString("zone_name");
	
            out.write("\r\n");
            out.write("\t<option value=\"");
            out.print(zname2);
            out.write('"');
            out.write('>');
            out.print(zname2);
            out.write("</option>\r\n");
            out.write("\t");

		}
	}
	
            out.write("\t\t\t</select> <br /> <br />\r\n");
            out.write("\t\t\t\r\n");
            out.write("\r\n");
            out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Division of Railway:\r\n");
            out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t<br>\r\n");
            out.write("        \t<div style='display: inline;' id='state");
            out.print(i);
            out.write("'>\r\n");
            out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t<div style='display: inline;' id = 'state2");
            out.print(i);
            out.write("'></div><br>  <!--  division2 -->\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Project Director:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\t\t\t\t\r\n");
            out.write("\t\t\t<input type=\"text\" name=\"projectinCharge");
            out.print(i);
            out.write("\" id =\"projectinCharge");
            out.print(i);
            out.write("\"  maxlength=\"50\" style=\"width: 205px\"> <br /><br />\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Department:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t");

			String piu =(String)pageContext.getAttribute("PIU",PageContext.SESSION_SCOPE);
			
			
            out.write("\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t  \t\t\t  \r\n");
            out.write("\t\t\t\t  <select name='Department_RVNL");
            out.print(i );
            out.write("' id='Department_RVNL");
            out.print(i);
            out.write("' style=\"width: 205px\" onchange='show1(");
            out.print(i);
            out.write(");'>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"\">Select Department</option>\r\n");
            out.write("\t\t\t\t\t\t");

						 dep_rs = stmt.executeQuery("select department_name from xx_departments_master where type ='RVNL' and Department_Name !='Headquarter' order by department_name");
						String dep_name = null;
						while (dep_rs.next()) {
						dep_name = dep_rs.getString("Department_Name");
					
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.print(dep_name);
            out.write('"');
            out.write('>');
            out.print(dep_name);
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t");

						}						
						
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t     \t</select> \r\n");
            out.write("\t\t\t\t  <br /> <br />\r\n");
            out.write("\t\t\t\t\t\t\t  \r\n");
            out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Designation:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t\t<div id =\"DesgDiv_RVNL");
            out.print(i);
            out.write("\" style=\"display: inline;\">\r\n");
            out.write("\t\t\t\t\t<select name='designation_RVNL");
            out.print(i);
            out.write("' id='designation_RVNL");
            out.print(i);
            out.write("' style=\"width: 205px;margin:3px 0px 12px 0px;\">\r\n");
            out.write("\t\t\t\t\t\t<option value=\"\">Select Designation</option>\t\t\t\t\t\t  \r\n");
            out.write("\t\t\t\t</select> <br /> <br /></div>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
            out.write("var $drops");
            out.print(i);
            out.write(" = $('.drop");
            out.print(i);
            out.write("'),\r\n");
            out.write("    // store a set of options\r\n");
            out.write("    $options");
            out.print(i);
            out.write(" = $drops");
            out.print(i);
            out.write(".eq(1).children().clone();\r\n");
            out.write("\r\n");
            out.write("$drops");
            out.print(i);
            out.write(".change(function(){\r\n");
            out.write("    var $other");
            out.print(i);
            out.write(" = $drops");
            out.print(i);
            out.write(".not(this),\r\n");
            out.write("        otherVal");
            out.print(i);
            out.write(" = $other");
            out.print(i);
            out.write(".val(),\r\n");
            out.write("        newVal");
            out.print(i);
            out.write(" = $(this).val(),\r\n");
            out.write("        $opts");
            out.print(i);
            out.write(" = $options");
            out.print(i);
            out.write(".clone().filter(function(){\r\n");
            out.write("           return this.value !== newVal");
            out.print(i);
            out.write("; \r\n");
            out.write("        })\r\n");
            out.write("     $other");
            out.print(i);
            out.write(".html($opts");
            out.print(i);
            out.write(").val(otherVal");
            out.print(i);
            out.write(");\r\n");
            out.write("    \r\n");
            out.write("})\r\n");
            out.write("</script>\t\r\n");
            out.write("\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t <td width=\"35%\"> \t<br><center> <h5 Style=\"color:gray;\"><b>Details of Documents/ Drgs required for the Package</b></h5></center><br>\r\n");
            out.write("\t\t\t\t <table class=\"table table-hover table-bordered\"  align=\"center\" style=\"background-color: #F0FFFF; \">\r\n");
            out.write("\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<th width=\"50px\" >S. No.</th> <th > Document/ Drg Type </th> <th width=\"150px\"> Nos. of Documents/ Drgs Required</th></tr>\r\n");
            out.write("\t\t\t\t\r\n");

            int j3=0;
				 drg_rs7 = stmt.executeQuery("select * from xx_documentattributes_master order by Document_Type");
						String drgtyp = null, drgid =null, nosreqd=null;
					while (drg_rs7.next()) {
						drgtyp = drg_rs7.getString("Document_Type");
						drgid = drg_rs7.getString("Document_Type_Id");
						//nosreqd = drg_rs7.getString("Nos_Reqd");
					if (nosreqd==null) {nosreqd="";}	
				
            out.write("\r\n");
            out.write("\t\t\t\t<tr><td>");
            out.print(j3+1 );
            out.write(".</td> <td>");
            out.print(drgtyp );
            out.write(":</td>\r\n");
            out.write("\t\t\t\t<td> <center><input type=\"text\" pattern=\"\\d+\"  oninput=\"this.value=this.value.replace(/[^0-9]/g,'');\" name=\"no_drg");
            out.print(i);
            out.write('_');
            out.print(j3 );
            out.write("\" id =\"no_drg");
            out.print(i);
            out.write('_');
            out.print(j3 );
            out.write("\"   style=\"width: 50px; \"></center>\r\n");
            out.write("\t\t\t\t<input type=\"hidden\" name=\"drgid");
            out.print(i);
            out.write('_');
            out.print(j3 );
            out.write("\"  value=");
            out.print(drgid );
            out.write("></td></tr>\t\r\n");
            out.write("\t\t\t");

			j3++;
		}	
				
	
            out.write("\t\r\n");
            out.write("</table>\r\n");
            out.write("<INPUT TYPE=\"hidden\" NAME=\"nosofDrg");
            out.print(i);
            out.write("\" ID=\"nosofDrg");
            out.print(i);
            out.write("\" value=");
            out.print(j3);
            out.write(">\t\t\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\r\n");
            out.write("\t\t\t");

			//i++; 
			//}
				
				
				//con.close();
				 }
						catch(Exception e){
						
						e.printStackTrace();
						} finally {
						    try { rs21.close(); } catch (Exception e) { /* ignored */ }
						    try { rs31.close(); } catch (Exception e) { /* ignored */ }
						    try { rs311.close(); } catch (Exception e) { /* ignored */ }
						    try { rs32.close(); } catch (Exception e) { /* ignored */ }
						    try { rs312.close(); } catch (Exception e) { /* ignored */ }
						    try { dep_rs.close(); } catch (Exception e) { /* ignored */ }
						    try { drg_rs7.close(); } catch (Exception e) { /* ignored */ }
						    try { con.close(); } catch (Exception e) { /* ignored */ }
						}
				
				
			
			 
            out.write("\r\n");
            out.write("\t\t\t </td>\r\n");
            out.write("\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t<br><br>\r\n");
            out.write("\t\t\t\t <center> <button type=\"button\" id=\"btnclick\" class=\"btn btn-primary\" onclick=\"javascript:packageupdate();\" style=\"margin-left:100px\">ADD</button> \r\n");
            out.write("       \r\n");
            out.write("      &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; <input type=\"reset\" class=\"btn btn-primary\" value=\"Cancel\" onClick=\"refreshAndClose()\" style=\"margin-left:200px\"/></center><br><br>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t \r\n");
            out.write("\t\t\t<div id=\"dialogid1\" style=\"display: none\"\r\n");
            out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<br> Please Select Different Package Name<br>\r\n");
            out.write("\t\t\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t\t\t\t<button id=\"cancle\" class=\"btn btn-primary\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tonclick=\"$('#dialogid1').dialog('close');\">cancel</button>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("       \r\n");
            out.write("\t\t<div id=\"dialogid\" style=\"display: none\"\r\n");
            out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<br> Please Fill All Data<br>\r\n");
            out.write("\t\t\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t\t\t\t<button id=\"cancle\" class=\"btn btn-primary\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tonclick=\"jQuery.noConflict();$('#dialogid').dialog('close');\">cancel</button>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /Admin/addmorepackage.jsp(561,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.Project_stage != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");


String Package0 = request.getParameter("Package0");
String start_Date = request.getParameter("pacstart_Date0");
 String projectid = request.getParameter("projectidmain");

String Railway0 = request.getParameter("Railway0");
String projectinCharge0 = request.getParameter("projectinCharge0");
String Department_RVNL0 = request.getParameter("Department_RVNL0");
String designation_RVNL0 = request.getParameter("designation_RVNL0");
String pacstart_Date0=null;
Date initDate = new SimpleDateFormat("dd/MM/yyyy").parse(start_Date);
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
pacstart_Date0 = formatter.format(initDate);

Connection conn = null;
ResultSet  rs2=null,rspiuuid11=null,rspiu1=null,rspiu=null,rspiuid=null,rspiuuid=null;

try{
Context initCtx = new InitialContext();
Context envCtx = (Context) initCtx.lookup("java:comp/env");
DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
 conn = ds.getConnection();
Statement seq_stmt = conn.createStatement();
//java.util.ArrayList<String> userlistal1 = new java.util.ArrayList<String>();
Set<String> userlistal1 = new TreeSet<String>(String.CASE_INSENSITIVE_ORDER);
String sqlpiuuid11="select DISTINCT(package_name) from xx_packages_project where project_id="+projectid;  
Statement stmtpiuuid11 = conn.createStatement();
	 rspiuuid11 = stmtpiuuid11.executeQuery(sqlpiuuid11);
	String package_name11=null;
while(rspiuuid11.next()){
	package_name11=rspiuuid11.getString("package_name");
	userlistal1.add(package_name11);
	}

//System.out.println("coming final---------"+!userlistal1.contains(Package0)+"second-----------"+userlistal1.contains(Package0));
if(userlistal1.contains(Package0)){
	
	
	
            out.write("\t\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<div class=\"alert alert-danger\"><br>\r\n");
            out.write("\t <strong>Alert!</strong> Packages Name should be different !\r\n");
            out.write("\t <br>\r\n");
            out.write("\t <br>\r\n");
            out.write("\t <input class='btn btn-primary' value='ok'  onClick=\"refreshAndClose()\" type='button'/>\r\n");
            out.write("\t </div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t");

}else{
	//System.out.println("Coming here------insidne else");

            out.write('\r');
            out.write('\n');
            out.write(' ');
            //  sql:update
            org.apache.taglibs.standard.tag.rt.sql.UpdateTag _jspx_th_sql_005fupdate_005f0 = (org.apache.taglibs.standard.tag.rt.sql.UpdateTag) _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.UpdateTag.class);
            boolean _jspx_th_sql_005fupdate_005f0_reused = false;
            try {
              _jspx_th_sql_005fupdate_005f0.setPageContext(_jspx_page_context);
              _jspx_th_sql_005fupdate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /Admin/addmorepackage.jsp(617,1) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_sql_005fupdate_005f0.setDataSource("jdbc/MySQLDB");
              // /Admin/addmorepackage.jsp(617,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_sql_005fupdate_005f0.setVar("rs");
              int[] _jspx_push_body_count_sql_005fupdate_005f0 = new int[] { 0 };
              try {
                int _jspx_eval_sql_005fupdate_005f0 = _jspx_th_sql_005fupdate_005f0.doStartTag();
                if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    _jspx_push_body_count_sql_005fupdate_005f0[0]++;
                    out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fupdate_005f0);
                  }
                  do {
                    out.write("\r\n");
                    out.write("\t   INSERT INTO xx_packages_project (project_id,package_name,packageStartDate,department,designation,package_director) VALUES ('");
                    out.print(projectid);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(Package0);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(pacstart_Date0);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(Department_RVNL0);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(designation_RVNL0);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(projectinCharge0);
                    out.write("');\r\n");
                    out.write("\t");
                    int evalDoAfterBody = _jspx_th_sql_005fupdate_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                  if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    out = _jspx_page_context.popBody();
                    _jspx_push_body_count_sql_005fupdate_005f0[0]--;
                  }
                }
                if (_jspx_th_sql_005fupdate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
              } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_sql_005fupdate_005f0[0]-- > 0)
                  out = _jspx_page_context.popBody();
                _jspx_th_sql_005fupdate_005f0.doCatch(_jspx_exception);
              } finally {
                _jspx_th_sql_005fupdate_005f0.doFinally();
              }
              _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fupdate_005f0);
              _jspx_th_sql_005fupdate_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fupdate_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fupdate_005f0_reused);
            }
            out.write(' ');
            out.write('\r');
            out.write('\n');



String sqlprojectid="select package_id from xx_packages_project where project_id='"+projectid+"' order by package_id desc limit 1";
Statement stmtpiu1 = conn.createStatement();
 rspiu1 = stmtpiu1.executeQuery(sqlprojectid);
String packageid11=null;
while(rspiu1.next()){
	packageid11=rspiu1.getString("package_id");

}
String sqlpiu="select PIU_of_RVNL from xx_projectattributes_master where Project_ID="+projectid;  
Statement stmtpiu = conn.createStatement();
	 rspiu = stmtpiu.executeQuery(sqlpiu);
	String piun=null;
while(rspiu.next()){
	piun=rspiu.getString(1);
	}
String sqlpiuid="select PIU_Id from xx_piu_master where PIU_Name='"+piun+"'";  
Statement stmtpiuid = conn.createStatement();
	 rspiuid = stmtpiuid.executeQuery(sqlpiuid);
	String piunid=null;
while(rspiuid.next()){
	piunid=rspiuid.getString(1);
	}
String sqlpiuuid="select distinct User_Id from xx_user_zone_mapping where piu_id="+piunid;  
Statement stmtpiuuid = conn.createStatement();
	 rspiuuid = stmtpiuuid.executeQuery(sqlpiuuid);
	String piuuid=null;
while(rspiuuid.next()){
	piuuid=rspiuuid.getString(1);
	}

String divisions="";
//String projectid="";
//String packageids=null;
String name="pacstart_Date0";
String deptRVNLid="Department_RVNL0";
String desgRVNLid="designation_RVNL0";
String packCoordinatorId="projectinCharge0";

String sdate=request.getParameter(name);
String deptRVNL=request.getParameter(deptRVNLid);
String desgRVNL=request.getParameter(desgRVNLid);
String packCoordinator=request.getParameter(packCoordinatorId);
		

Date date =new SimpleDateFormat("dd/MM/yyyy").parse(sdate);
java.sql.Date st = new java.sql.Date(date.getTime());
String package1id="";String package2id="";String package3id="";String package4id="";String package5id="";
	
	Set<String> zone_ids = new HashSet<String>();
	String[] divisioncheck ;
		for(int j=1;j<=2;j++){
				 name="divisions"+j+":"+i;	
				divisioncheck = request.getParameterValues(name);
				divisions=divisions+"::Zone"+j+":"+i;
				if (divisioncheck != null) 
				{
		 		  for (int k = 0; k < divisioncheck.length; k++) {
		 			
		 			// conn = ds.getConnection();
		 			  
		 			 Statement stmt = conn.createStatement();
						 rs2 = stmt.executeQuery("select ext_zone_id from xx_divisions_map where division_name = '"+divisioncheck[k]+"'");

						String z_id = null;

						while (rs2.next()) {
							z_id = rs2.getString(1); 
							zone_ids.add(z_id);
									
						}
		 			  
						
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            //  sql:update
            org.apache.taglibs.standard.tag.rt.sql.UpdateTag _jspx_th_sql_005fupdate_005f1 = (org.apache.taglibs.standard.tag.rt.sql.UpdateTag) _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.UpdateTag.class);
            boolean _jspx_th_sql_005fupdate_005f1_reused = false;
            try {
              _jspx_th_sql_005fupdate_005f1.setPageContext(_jspx_page_context);
              _jspx_th_sql_005fupdate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /Admin/addmorepackage.jsp(695,6) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_sql_005fupdate_005f1.setDataSource("jdbc/MySQLDB");
              // /Admin/addmorepackage.jsp(695,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_sql_005fupdate_005f1.setVar("rs");
              int[] _jspx_push_body_count_sql_005fupdate_005f1 = new int[] { 0 };
              try {
                int _jspx_eval_sql_005fupdate_005f1 = _jspx_th_sql_005fupdate_005f1.doStartTag();
                if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    _jspx_push_body_count_sql_005fupdate_005f1[0]++;
                    out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fupdate_005f1);
                  }
                  do {
                    out.write("\r\n");
                    out.write("\t\t\t\t\t\t   INSERT INTO xx_project_division_map (package_id,division_name,zone_id) VALUES ('");
                    out.print(packageid11);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(divisioncheck[k]);
                    out.write('\'');
                    out.write(',');
                    out.write('\'');
                    out.print(z_id);
                    out.write("');\r\n");
                    out.write("\t\t\t\t\t\t");
                    int evalDoAfterBody = _jspx_th_sql_005fupdate_005f1.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                  if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    out = _jspx_page_context.popBody();
                    _jspx_push_body_count_sql_005fupdate_005f1[0]--;
                  }
                }
                if (_jspx_th_sql_005fupdate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
              } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_sql_005fupdate_005f1[0]-- > 0)
                  out = _jspx_page_context.popBody();
                _jspx_th_sql_005fupdate_005f1.doCatch(_jspx_exception);
              } finally {
                _jspx_th_sql_005fupdate_005f1.doFinally();
              }
              _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fupdate_005f1);
              _jspx_th_sql_005fupdate_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fupdate_005f1, _jsp_getInstanceManager(), _jspx_th_sql_005fupdate_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
	
					
						
		 			 divisions=divisions+"~"+divisioncheck[k];
				
					}
		      }	
		}
	
/*	
	*/
	String nosdrg1=request.getParameter("nosofDrg"+i);
				int nosdrg =Integer.parseInt(nosdrg1);
		for(int j2=0;j2<nosdrg;j2++){				
			String drgid=request.getParameter("drgid"+i+"_"+j2);
			String nosreqd=request.getParameter("no_drg"+i+"_"+j2);
			
			
            out.write("\r\n");
            out.write("\t\t\t");
            //  sql:update
            org.apache.taglibs.standard.tag.rt.sql.UpdateTag _jspx_th_sql_005fupdate_005f2 = (org.apache.taglibs.standard.tag.rt.sql.UpdateTag) _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.UpdateTag.class);
            boolean _jspx_th_sql_005fupdate_005f2_reused = false;
            try {
              _jspx_th_sql_005fupdate_005f2.setPageContext(_jspx_page_context);
              _jspx_th_sql_005fupdate_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
              // /Admin/addmorepackage.jsp(716,3) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_sql_005fupdate_005f2.setDataSource("jdbc/MySQLDB");
              int[] _jspx_push_body_count_sql_005fupdate_005f2 = new int[] { 0 };
              try {
                int _jspx_eval_sql_005fupdate_005f2 = _jspx_th_sql_005fupdate_005f2.doStartTag();
                if (_jspx_eval_sql_005fupdate_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  if (_jspx_eval_sql_005fupdate_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    _jspx_push_body_count_sql_005fupdate_005f2[0]++;
                    out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fupdate_005f2);
                  }
                  do {
                    out.write("\r\n");
                    out.write("\t\t\t  insert into xx_project_docnos (Project_Id, Package_Id, Document_Type_Id, Nos_Reqd) VALUES (");
                    out.print(projectid);
                    out.write(',');
                    out.write(' ');
                    out.print(packageid11);
                    out.write(',');
                    out.print(drgid);
                    out.write(',');
                    out.print(nosreqd);
                    out.write(");\r\n");
                    out.write("\t\t\t");
                    int evalDoAfterBody = _jspx_th_sql_005fupdate_005f2.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                  if (_jspx_eval_sql_005fupdate_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                    out = _jspx_page_context.popBody();
                    _jspx_push_body_count_sql_005fupdate_005f2[0]--;
                  }
                }
                if (_jspx_th_sql_005fupdate_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
              } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_sql_005fupdate_005f2[0]-- > 0)
                  out = _jspx_page_context.popBody();
                _jspx_th_sql_005fupdate_005f2.doCatch(_jspx_exception);
              } finally {
                _jspx_th_sql_005fupdate_005f2.doFinally();
              }
              _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fdataSource.reuse(_jspx_th_sql_005fupdate_005f2);
              _jspx_th_sql_005fupdate_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fupdate_005f2, _jsp_getInstanceManager(), _jspx_th_sql_005fupdate_005f2_reused);
            }
            out.write('\r');
            out.write('\n');
 
}	
	
	
	
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 100px 100px 100px 100px\" ><br>\r\n");
            out.write("\t <strong>Success!</strong> Package Added successfully.\r\n");
            out.write("\t <br>\r\n");
            out.write("\t <br>\r\n");
            out.write("\t <center><input class='btn btn-primary' value='ok'  onClick=\"refreshAndClose()\" type='button'/></center>\r\n");
            out.write("\t </div>\r\n");
            out.write("\t\r\n");
            out.write("\r\n");

}
	



userlistal1.clear();
//conn.close();
} catch(Exception e) {
	e.printStackTrace();
} finally {
    try { rspiuuid11.close(); } catch (Exception e) { /* ignored */ }
    try { rspiu1.close(); } catch (Exception e) { /* ignored */ }
    try { rspiu.close(); } catch (Exception e) { /* ignored */ }
    try { rspiuid.close(); } catch (Exception e) { /* ignored */ }
    try { rspiuuid.close(); } catch (Exception e) { /* ignored */ }
    try { rs2.close(); } catch (Exception e) { /* ignored */ }
    try { conn.close(); } catch (Exception e) { /* ignored */ }
}


            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \r\n");
      out.write("\r\n");
      out.write("</body><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,700');\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tmargin-top:150px;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"city\">\r\n");
      out.write("  <ul class=\" nav navbar-nav\">\r\n");
      out.write("  \r\n");
      out.write("    <li class=\"footerli\">Rail Vikas Nigam Limited.</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul   class=\"nav navabar-nav\" style=\"float:right;\">\r\n");
      out.write("   <li class=\"footerli\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Design & Developed By<a href=\"http://www.awcsoftware.net\" style=\"text-decoration:none;\">AWC SOFTWARE PVT LTD</a></li>\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</footer> -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer-basic-centered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\" style=\"float:left;\">Rail Vikas Nigam Limited</p>\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\" style=\"float:center; font-family:serif; font-size:14px; font-style:italic; margin-top:5px;\">Ver:2.30.pks</p>\r\n");
      out.write("\t\t\t<p class=\"footer-company-name\" style=\"float:right; margin-top:-20px;\"> Design & Developed By<a href=\"http://www.awcsoftware.net\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AWC SOFTWARE PVT LTD</a></p>\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
