/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.86
 * Generated at: 2018-05-22 12:35:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;

public final class admn_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Admin/included/footer.jsp", Long.valueOf(1526635913268L));
    _jspx_dependants.put("/WEB-INF/sessionCheck1.jspf", Long.valueOf(1524567358000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
int timeout = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout + "; URL = admn_login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>  \r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Application/Admin/resources/bootstrap-3.3.7-dist/css1/bootstrap.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Application/Admin/resources/css/main.css\"/>\t\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/PDAMS_icon.ico\" />\r\n");
      out.write("<title>PDAMS Login</title>\r\n");
      out.write("<script src=\"resources/JS/validateSysAdmin230.js\"></script>\r\n");
      out.write("<SCRIPT type=\"text/javascript\">\r\n");
      out.write("    window.history.forward();\r\n");
      out.write("    function noBack() { window.history.forward(); }\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div.gallery {\r\n");
      out.write("    margin: 2px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery:hover {\r\n");
      out.write("    border: 1px solid #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100px;                                           \r\n");
      out.write("   background-image:cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.desc {\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#header {\r\n");
      out.write("    background-color:#580058;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("html, body {\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("  border: 0px;\r\n");
      out.write("}\r\n");
      out.write(".header\r\n");
      out.write("{\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("width:auto;\r\n");
      out.write("height:80px;\r\n");
      out.write("background-color:#8C001A;\r\n");
      out.write("}\r\n");
      out.write("ul\r\n");
      out.write("{\r\n");
      out.write("float:left;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("ul li\r\n");
      out.write("{\r\n");
      out.write("float:left;\r\n");
      out.write("margin-left:30px;\r\n");
      out.write("list-style-type:none;\r\n");
      out.write("border-right:1px dotted white;\r\n");
      out.write("margin-bottom:10px;\r\n");
      out.write("padding-bottom:15px;\r\n");
      out.write("margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write("ul li a\r\n");
      out.write("{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("color:white;\r\n");
      out.write("display:block;\r\n");
      out.write("padding:5px;\r\n");
      out.write("margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write("ul li a:hover\r\n");
      out.write("{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".topmenu\r\n");
      out.write("{\r\n");
      out.write("background-color:#C11B17;\r\n");
      out.write("height:40px;\r\n");
      out.write("width: auto;\r\n");
      out.write("}\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("font-family:'Aerial';\r\n");
      out.write("font-size:16px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("     word-wrap: break-word;\r\n");
      out.write("     -webkit-hyphens: auto;\r\n");
      out.write("     -moz-hyphens: auto;\r\n");
      out.write("     -ms-hyphens: auto;\r\n");
      out.write("     -o-hyphens: auto;\r\n");
      out.write("     hyphens: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "included/NewHeader1.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("theme3", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("brown", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--    <div class=\"header\">\r\n");
      out.write("   <table><tr><td width=15%>\r\n");
      out.write("    \t\t  <img src=\"images/rail.png\" class=\"img-responsive\" style=\"float:left;height:80px;margin-left:0px;\"><br>\r\n");
      out.write("    \t\t  \r\n");
      out.write("   </td>\r\n");
      out.write("   <td width=60%>\r\n");
      out.write("      \t\t <h2 style=\"color:white;\"><i>Project Documents Approval Monitoring System (PDAMS)</i></h2>\t\r\n");
      out.write("   \r\n");
      out.write("   </td><td width=25%>\r\n");
      out.write(" \t\t  <img src=\"images/logo.png\" class=\"img-responsive\" style=\"float:right;height:80px;margin-right:0px;\">\r\n");
      out.write(" \t\t  <br></td></tr>\r\n");
      out.write("   </table></div> -->\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<div class=\"container-fluid bg_img\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\"></div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"col-3 col-s-12\"></div>\r\n");
      out.write("<form id=\"loginPage\" class=\"bg_login\" name=\"loginPage\" method=\"post\" action=\"login_success.jsp\" >\r\n");
      out.write("<img class=\"logo\" src=\"/Application/Admin/images/Rail_logo.png\" alt=\"\" class=\"img-responsive\"/>\r\n");
      out.write("<h1 class=\"welcome\">Welcome</h1>\r\n");
      out.write("    ");

    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1.
    response.setHeader("Pragma", "no-cache"); // HTTP 1.0.
    response.setHeader("Expires", "0"); // Proxies.
    String msg1=null, msg2=null, msg3=null, pic1=null, pic2=null, pic3=null, profile_alert=null, docaction_alert=null;					
		
    String error=null;
            error=(String)session.getValue("u_error");
            if(error==null)   {
                 Connection conn2 = null;
     			PreparedStatement ps227=null;
     			ResultSet  rs227=null;
     						//Statement stmt = null;
     						try {
     							Context initCtx = new InitialContext();
     							Context envCtx = (Context) initCtx.lookup("java:comp/env");
     							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");

     							conn2 = ds.getConnection();
     							String sql35 = "select item, description from xx_maintenance";
     									
    								ps227 = conn2.prepareStatement(sql35);
    								rs227 = ps227.executeQuery();
    								while (rs227.next()) {
    									String item=rs227.getString(1);
    									 String desc=rs227.getString(2);
    								 if (item.equalsIgnoreCase("msg-1")) {
    										msg1=desc;
    									} else if (item.equalsIgnoreCase("msg-2")) {
    										msg2=desc;
    									} else if (item.equalsIgnoreCase("msg-3")) {
    										msg3=desc;
    									}
    								 if (item.equalsIgnoreCase("pic-1")) {
 										pic1=desc;
 									} else if (item.equalsIgnoreCase("pic-2")) {
 										pic2=desc;
 									} else if (item.equalsIgnoreCase("pic-3")) {
 										pic3=desc;
 									} else if (item.equalsIgnoreCase("profile_alert")) {
 										profile_alert=desc;
 										session.setAttribute("Profile_Alert",profile_alert);
 									} else if (item.equalsIgnoreCase("doc_action_alert")) {
 										docaction_alert=desc;
 										session.setAttribute("doc_action_Alert",docaction_alert);
 									}
    								}
    									
     						}catch(Exception e){
    							
    							e.printStackTrace();
    						}  finally {
     						    try { rs227.close(); } catch (Exception e) { /* ignored */ }
     						    try { ps227.close(); } catch (Exception e) { /* ignored */ }
     						    try { conn2.close(); } catch (Exception e) { /* ignored */ }
     						}


              									
      out.write("\r\n");
      out.write("                    \t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                   <!--  <div> <font size=\"5vw\"  style=margin-left:45%; color:Blue; font-family: calibri;\">Welcome</font></div>-->\r\n");
      out.write("                   \r\n");
      out.write("                   ");

                }
            else if(error.equals("relogin"))
                {
            
      out.write("\r\n");
      out.write("            <font size=\"4\" style=\"color:red;font-family: calibri;\">Try Again</font>\r\n");
      out.write("            \r\n");
      out.write("            ");

                session.putValue("u_error",null);
            }
   
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Username</label>\r\n");
      out.write("    <input type=\"user_name\" name=\"user_name\" class=\"form-control\" id=\"user_name\" aria-describedby=\"emailHelp\" placeholder=\"Enter UserName\">\r\n");
      out.write("    <small id=\"emailHelp\" class=\"form-text text-muted\" style=color:#FFA500;>We'll never share your email with anyone else.</small>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password</label>\r\n");
      out.write("    <input type=\"password\" name=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Password\">\r\n");
      out.write("  </div>\r\n");
      out.write("  ");

               //In order to bring transparency and enable monitoring of approval of various plans/documents submitted by project authorities to Railway Officials in Divisions and Zonal Headquarters, RVNL has made a beginning by developing a web-based application 'Project Documents Approval Monitoring System (PDAMS) '.  <br> <b>- MR</b>
               //RPDAMS will log movement of plans/documents right from submission till approval by all concerned officials. MIS reports generated from the application will help in monitoring the progress of approvals at divisional and HQ levels. Periodic reports sent by portal through weekly emails to DRMs and GMs will act as a managerial information tool to ensure speedier approvals of project documents with ultimate objective of faster project delivery.  <br> <b>- CMD/RVNL</b>
String error1 = "";
error1 = (String)session.getAttribute("error");
if(error1!=null)
out.println(error1);
session.setAttribute("error", null);

      out.write("\r\n");
      out.write("  <div class=\"form-check\">\r\n");
      out.write("    <input type=\"checkbox\" class=\"form-check-input\" id=\"exampleCheck1\">\r\n");
      out.write("    <label class=\"form-check-label\" for=\"exampleCheck1\">Remember me</label>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br> \r\n");
      out.write("        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success btn-block\" value=\"Login\" onclick=\"javascript:validateUser();\">Login</button>\r\n");
      out.write("  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <input class=\"btn btn-success btn-block\" style=\"margin-top:-10px;\" type=\"button\" onclick=\"javascript:location.reload();\" value=\"Reset\" />\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \t\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("</form> \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Application/Admin/resources/bootstrap-3.3.7-dist/css1/bootstrap.css\"/>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,700');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer-basic-centered{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft:0px;\r\n");
      out.write("   \r\n");
      out.write("\tmargin-top:0px;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("}\r\n");
      out.write("html {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  min-height: 100%;\r\n");
      out.write("}\r\n");
      out.write("@media (max-height:800px){\r\n");
      out.write("\tfooter { position: static; }\r\n");
      out.write("\theader { padding-top:0px; }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-basic-centered{\r\n");
      out.write("\tbackground-color:#8C001A; //#003399;\r\n");
      out.write("\tbox-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont: normal 18px sans-serif;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-basic-centered .footer-company-motto{\r\n");
      out.write("\tcolor:  #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-basic-centered .footer-company-name{\r\n");
      out.write("\tcolor:  #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* If you don't want the footer to be responsive, remove these media queries */\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("\r\n");
      out.write("\t.footer-basic-centered{\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t\t//bottom:0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.footer-basic-centered .footer-company-motto{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.footer-basic-centered .footer-company-name{\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"city\">\r\n");
      out.write("  <ul class=\" nav navbar-nav\">\r\n");
      out.write("  \r\n");
      out.write("    <li class=\"footerli\">Rail Vikas Nigam Limited.</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul   class=\"nav navabar-nav\" style=\"float:right;\">\r\n");
      out.write("   <li class=\"footerli\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Design & Developed By<a href=\"http://www.awcsoftware.net\" style=\"text-decoration:none;\">AWC SOFTWARE PVT LTD</a></li>\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</footer> -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer-basic-centered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\" style=\"float:left;\">Rail Vikas Nigam Limited</p>\r\n");
      out.write("            <p class=\"footer-company-motto\" style=\"float:right; font-family:serif; font-size:14px; font-style:italic; margin-top:0px;\">Ver:2.30.pks</p> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\t\r\n");
      out.write("   </div> \r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("   <script type=\"text/javascript\" src=\"/Application/Admin/resources/bootstrap-3.3.7-dist/js/jquery-3.3.1.js\"></script> \r\n");
      out.write("   <script type=\"text/javascript\" src=\"resources/bootstrap-3.3.7-dist/js/bootstrap.js\"></script>   \t\t     \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
