/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.86
 * Generated at: 2018-05-24 04:52:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import java.io.FileOutputStream;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;

public final class datesetting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Admin/included/NewHeader.jsp", Long.valueOf(1527076887650L));
    _jspx_dependants.put("/WEB-INF/sessionCheck1.jspf", Long.valueOf(1524567358000L));
    _jspx_dependants.put("/Admin/included/Newfooter.jsp", Long.valueOf(1526628672412L));
    _jspx_dependants.put("/Admin/sessionCheck.jsp", Long.valueOf(1524567356000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 1120256, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
int timeout = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout + "; URL = admn_login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 

int timeout1 = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout1 + "; URL = admn_login.jsp");

if(((String)session.getAttribute("user_name"))==null)
       {
           
	response.sendRedirect("admn_login.jsp");
           
       }
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

 String theme3 = (String) pageContext.getAttribute("myTheme", PageContext.SESSION_SCOPE);
if (theme3!=null) {
if (theme3.equalsIgnoreCase("brown") ) { 
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
 } else if (theme3.equalsIgnoreCase("blue")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBlue.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("green")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmGreen.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("magenta")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/Thmmagenta.css\">\r\n");
      out.write("\t\t");
}
} else {
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>PDAMS</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".white-marquee {\r\n");
      out.write("   font-family:   arial, serif, \"Times New Roman\", calibri, Times;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor:  white;\r\n");
      out.write("\t//margin-left:50px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tpadding-bottom:5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");

//String mailstatus=(String)session.getAttribute("MailStatus"); 
//String user = (String) session.getAttribute("user_name");
String user_code = (String) session.getAttribute("User_Code");
if (user_code!=null) {} else {user_code="0";}
 String mq=null, mqLaunch=null, mqMaint=null, mqOther=null, mqRly=null, mqRVNL=null;					
 //System.out.println("code="+user_code);	
  Connection conn7 = null;
     			PreparedStatement ps777=null;
     			ResultSet  rs777=null;
     						//Statement stmt7 = null;
     						try {
     							Context initCtx = new InitialContext();
     							Context envCtx = (Context) initCtx.lookup("java:comp/env");
     							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");

     							conn7 = ds.getConnection();
     							String sql35 = "select item, description from xx_maintenance";
     									
    								ps777 = conn7.prepareStatement(sql35);
    								rs777 = ps777.executeQuery();
    								while (rs777.next()) {
    									String item=rs777.getString(1);
    									 String desc=rs777.getString(2);
    									if (item.equalsIgnoreCase("marquee-launch")) {
    										mqLaunch=desc;
    									} else if (item.equalsIgnoreCase("marquee-maint")) {
    										mqMaint=desc;
    									} else if (item.equalsIgnoreCase("marquee-other")) {
    										mqOther=desc;
    									} else if (item.equalsIgnoreCase("marquee-Rly")) {
    										mqRly=desc;
    									} else if (item.equalsIgnoreCase("marquee-RVNL")) {
    										mqRVNL=desc;
    									} 
    								}
    								if (user_code.equalsIgnoreCase("2")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRly;
    								} else if (user_code.equalsIgnoreCase("5")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRVNL;
    								} else {
    								mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther;
    								}		 
    				    				//System.out.println("marquee="+mq);
     						}catch(Exception e){
    							
    							e.printStackTrace();
    						} finally {
    						    try { rs777.close(); } catch (Exception e) { /* ignored */ }
    						    try { ps777.close(); } catch (Exception e) { /* ignored */ }
    						    try { conn7.close(); } catch (Exception e) { /* ignored */ }
    						}



      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"menu1\" value='");
      out.print(session.getAttribute("user_name") );
      out.write("'>\r\n");
      out.write("     \t   <div class=\"header\">\r\n");
      out.write("   \r\n");
      out.write(" \t\t   <table width=\"100%\"><tr><th width=15%>\r\n");
      out.write("    \t\t  <img src=\"images/Rail_logo.png\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write("    \t\t  \r\n");
      out.write("   </td>\r\n");
      out.write("   <th width=60%>\r\n");
      out.write("      \t\t <h2 style=\" margin-left:5px;\"><i>Project Documents Approval Monitoring System (PDAMS)</i></h2>\t\r\n");
      out.write("   \r\n");
      out.write("   </th><th width=25%>\r\n");
      out.write("\t  <img src=\"images/RVNL_LOGO.jpg\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write(" \t\t  </table>\t\r\n");
      out.write("   </div>\r\n");
      out.write("\t   <div class=\"topmenu\" id=\"menu\">\r\n");
      out.write("\t  <div id=\"menu1\"  style=\"float:left;\"> \r\n");
      out.write("\t  \t\t<ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<!-- <li><a href=\"user_index.jsp\">Add/Modify Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"user_Project.jsp\">My Projects</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"Reportpiuinitiate.jsp\">My Reports</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"MoreInfo.jsp\">Returned Tasks</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"PullBack.jsp\">PullBack Doc</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinalApproval.jsp\">Docs under Approval</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinallyApprovedShow.jsp\">Approved Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"ManualMail.jsp\">Reminders</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"User_List.jsp\">User List</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"changepasswordlocaladmin.jsp\">Change Password</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"helpmain.jsp\">Help</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"admn_logout.jsp\">Logout</a></li>  -->\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"NewIndex.jsp\">Home</a></li>\r\n");
      out.write("\t   \t\t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t</ul>\t \r\n");
      out.write("\t   \t\t\t\t\t</div>  \r\n");
      out.write("\t   \t\t\t\t\t");

	   					if (!mq.equalsIgnoreCase("") && mq!=null) {
	   					
      out.write("\t\r\n");
      out.write("\t   \t<div id=\"menu11\" ></div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t   <div id=\"menu2\"  style=\"width:70%; float:left;\">     \t\t\t\t\t\r\n");
      out.write("\t   <marquee><span class=\"white-marquee\" id=\"white-marquee\" style=\"float:right; width:100%\">");
      out.print(mq );
      out.write("</span></marquee>  </div>\r\n");
      out.write("\t  ");

	  	}
	   	
      out.write("\t\r\n");
      out.write("\t   \t\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Create User</title>\r\n");
      out.write("<link href=\"resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/JS/Approval_wf230.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<!--  <link\r\n");
      out.write("\thref=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" /> -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/JS/datasort.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/JS/datasort.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("#example_length {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("#example {\r\n");
      out.write("    width: inherit;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var people, asc1 = 1, asc2 = 1, asc3 = 1, asc4 = 1, asc5 = 1, asc6 = 1, asc7 = 1, asc8 = 1;\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("\tpeople = document.getElementById(\"people\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sort_table(tbody, col, asc) {\r\n");
      out.write("\tvar rows = tbody.rows, rlen = rows.length, arr = new Array(), i, j, cells, clen;\r\n");
      out.write("\t// fill the array with values from the table\r\n");
      out.write("\tfor (i = 0; i < rlen; i++) {\r\n");
      out.write("\t\tcells = rows[i].cells;\r\n");
      out.write("\t\tclen = cells.length;\r\n");
      out.write("\t\tarr[i] = new Array();\r\n");
      out.write("\t\tfor (j = 0; j < clen; j++) {\r\n");
      out.write("\t\t\tarr[i][j] = cells[j].innerHTML;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t// sort the array by the specified column number (col) and order (asc)\r\n");
      out.write("\tarr.sort(function(a, b) {\r\n");
      out.write("\t\treturn (a[col] == b[col]) ? 0\r\n");
      out.write("\t\t\t\t: ((a[col] > b[col]) ? asc : -1 * asc);\r\n");
      out.write("\t});\r\n");
      out.write("\t// replace existing rows with new rows created from the sorted array\r\n");
      out.write("\tfor (i = 0; i < rlen; i++) {\r\n");
      out.write("\t\trows[i].innerHTML = \"<td>\" + arr[i].join(\"</td><td>\") + \"</td>\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#example').DataTable( {\r\n");
      out.write("        columnDefs: [ {\r\n");
      out.write("            targets: [ 0 ],\r\n");
      out.write("            orderData: [ 0, 1 ]\r\n");
      out.write("        }, {\r\n");
      out.write("            targets: [ 1 ],\r\n");
      out.write("            orderData: [ 1, 0 ]\r\n");
      out.write("        }, {\r\n");
      out.write("            targets: [ 2 ],\r\n");
      out.write("            orderData: [ 2, 0 ]\r\n");
      out.write("        } ],\r\n");
      out.write("\t\t\t\"infoCallback\": function( settings, start, end, max, total, pre ) {\r\n");
      out.write("\t\t\tif (max==total) { return \"Showing \" + (end-start+1) + \"  of \" +total+\" records\"}\r\n");
      out.write("\t\t\telse {return \"Showing \" + (end-start+1) + \"  of \" +total+\" records (filtered from total \" + max+\" records)\"}\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("    } );\r\n");
      out.write("} );\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("div.absolute {\r\n");
      out.write("   \tposition:absolute;\r\n");
      out.write("   \tmargin-top: 5px;\r\n");
      out.write("   \tmargin-left: 55px;\r\n");
      out.write("   \tmargin-bottom: 20px;\r\n");
      out.write(" \tpadding: 15 px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    border: 3px double #ff4d4d;\r\n");
      out.write("    background-color:#ffe6e6;\r\n");
      out.write("     }\r\n");
      out.write("    table.center {\r\n");
      out.write("    margin-left:auto; \r\n");
      out.write("    margin-right:auto;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

response.setHeader("Cache-control","no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader("Expires", -1);

String role1=(String)session.getAttribute("role");
String role=(String)session.getAttribute("Type");
//String zone_id1=(String)session.getAttribute("zone_id"); 
//String piu_id1=(String)session.getAttribute("piu_id"); 

String user = (String)session.getAttribute("user_name");
//session.removeAttribute("RealdateStatus");
//System.out.println("UZER:"+user);

      out.write("\r\n");
      out.write("<div class=\"absolute\" style=\"font-weight:bold\" ><h8>&nbsp;&nbsp;&nbsp;[Date/Email Setting] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h8>\r\n");
      out.write("\r\n");
      out.write("<h8><font style=\"color:red; font-weight:normal\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome&nbsp;</font><font style=\"color:#3333cc; font-weight:normal\">:&nbsp;");
      out.print((String)session.getAttribute("user_name") );
      out.write("&nbsp;&nbsp;&nbsp;</font></h8>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" style=\"position:relative; margin-top:70px;\">\r\n");
      out.write("\t<form id=\"loginForm12\" name=\"loginForm12\" method=\"post\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"realdateoption\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"profilealertoption\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"docactionalertoption\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"manualalertoption\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"alertPIU\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"actionOption\">\t\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"Project_stage\">\r\n");
      out.write("\t<INPUT TYPE=\"HIDDEN\" NAME=\"MyProject_stage\">\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('	');
      out.write('\r');
      out.write('\n');
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /Admin/datesetting.jsp(165,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.MyProject_stage != null) and (param.Project_stage == '') }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t");

	//System.out.println("inside stage UZER:"+user);
	//String str99=request.getParameter("Project_stage0");
    //if(str99.equalsIgnoreCase("ninetynine")){	
		int count=1;;
		Connection conn = null;
		Statement stmt = null, stmt1=null,stmt2=null, stmt3=null;
		ResultSet rs = null,rs11=null, rs22=null,rs33=null, rs44=null;
		String des2=null, des=null, rdStatus=null, piu_id=null, piuname=null,piu_name=null,dep_name=null,desg_name=null,user_name=null,officername=null,email_id=null,contact_no=null,mailStatus=null,Action=null, Setting=null;
		Context initCtx = new InitialContext();
		Context envCtx = (Context) initCtx.lookup("java:comp/env");
		DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
		conn = ds.getConnection();
		try {
		String query2 = "select Description from  xx_maintenance where Item='profile_alert'";
		stmt2 = conn.createStatement();
		rs33 = stmt2.executeQuery(query2);
		if (rs33.next()) {
			 des = rs33.getString("Description");
		}
       	
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t\t<table style=\"margin: -16px 0px 0px 18px;\"><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>User's Profile Change Alert Setting :</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t<select name=\"profile1\" id=\"profile1\" style=\"width: 105px;\">\r\n");
            out.write("\t\t\t\t\t");
 if (des.equalsIgnoreCase("on")) { 
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<option value=\"on\" selected =\"selected\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\">Off</option>\r\n");
            out.write("\t\t\t\t\t\t");
} else {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"on\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\" selected =\"selected\">Off</option>\r\n");
            out.write("\t\t\t\t\t\t");
} 
            out.write("\r\n");
            out.write("\t\t\t\t</select><input type=\"button\" id=\"prof_update\" name=\"prof_update\" class=\"btn btn-primary\" value=\"update\" style=\"margin-left: 30px;\" onclick=\"prof_alert1();\"/><br><br></td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t");

			String query52 = "select Description from  xx_maintenance where Item='doc_action_alert'";
			stmt3 = conn.createStatement();
			rs44 = stmt3.executeQuery(query52);
			if (rs44.next()) {
				 des2 = rs44.getString("Description");
			}
	       	
			
            out.write("\r\n");
            out.write("\t\t\t\t\t<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Document Action Alert Setting :</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t<select name=\"docActionAlert1\" id=\"docActionAlert1\" style=\"width: 105px;\">\r\n");
            out.write("\t\t\t\t\t");
 if (des2.equalsIgnoreCase("on")) { 
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<option value=\"on\" selected =\"selected\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\">Off</option>\r\n");
            out.write("\t\t\t\t\t\t");
} else {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<option value=\"on\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\" selected =\"selected\">Off</option>\r\n");
            out.write("\t\t\t\t\t\t");
} 
            out.write("\r\n");
            out.write("\t\t\t\t</select><input type=\"button\" id=\"DocAction_update\" name=\"DocAction_update\" class=\"btn btn-primary\" value=\"update\" style=\"margin-left: 30px;\" onclick=\"doc_action_alert1();\"/><br><br></td>\t\r\n");
            out.write("</tr>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Real Time Date Setting :</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t<select name=\"realdate\" id=\"realdate\" style=\"width: 105px; margin-left:80px;\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<option value=\"on\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\">Off</option>\r\n");
            out.write("\t\t\t\t</select><input type=\"button\" id=\"dateset\" name=\"dateset\" class=\"btn btn-primary\" value=\"update\" style=\"margin-left: 30px;\" onclick=\"realdateset1();\"/><br><span style=\"font-size:12px; color:green; margin-left:50px;\">(for actual setting value please see table below)</span><br><br></td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Auto Alert/Reminder Setting :</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\r\n");
            out.write("\t<select name=\"piu\" id=\"piu\" style=\"width: 255px;\">\r\n");
            out.write("\t\t\t\t\t\t<option value=\"\">---Select PIU---</option>\t\r\n");
            out.write("\t\t");
	
		String query1 = "select distinct PIU_Name, PIU_ID from  xx_piu_master order by PIU_Name";
		stmt1 = conn.createStatement();
		rs22 = stmt1.executeQuery(query1);
		while (rs22.next()) {
			 piu_name= rs22.getString("PIU_Name");
			 piu_id = rs22.getString("PIU_Id");
       	 
            out.write("\r\n");
            out.write("       \t \t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<option value=\"");
            out.print(piu_id );
            out.write('"');
            out.write('>');
            out.print(piu_name );
            out.write("</option>\r\n");
            out.write("\t\t\t");

			}
			
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t<select name=\"manualAlert\" id=\"manualAlert\" style=\"width: 105px;\">\r\n");
            out.write("\t\t\t\t<option value=\"on\">On</option>\r\n");
            out.write("\t\t\t\t\t\t<option value=\"off\">Off</option>\r\n");
            out.write("\t\t\t\t\t\t</select>\r\n");
            out.write("\t\t\t\t<br><span style=\"font-size:12px; color:green; margin-left:50px;\">(for actual setting value please see table below)</span></td><td><input type=\"button\" id=\"dateset1\" name=\"dateset1\" class=\"btn btn-primary\" value=\"update\" style=\"margin-left: 30px; margin-top:-20px;\" onclick=\"manualalertset1();\"/></td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Delete Duplicate records :</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
            out.write("\t\t\t\t<br><span style=\"font-size:12px; color:green; margin-left:50px;\">(from xx_approval_workflow, xx_record_actions, xx_document_mapping)</span></td><td><input type=\"button\" id=\"deldoc1\" name=\"deldoc1\" class=\"btn btn-primary\" value=\"confirm delete\" style=\"margin-left: 30px;\" onclick=\"deldocset1();\"/></td>\t\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t</tr></table><br><br>\r\n");
            out.write("\t\t");

		String query = "select distinct PM.PIU_Name, usr.MailStatus, usr.RealdateStatus from  xx_piu_master PM, xx_user_master usr  where usr.PIU_ID = PM.PIU_Id order by PM.PIU_Name";
		
		stmt = conn.createStatement();
		rs = stmt.executeQuery(query);
		
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<table class=\"table table-hover table-bordered\" id=\"example\" class=\"display\"\r\n");
            out.write("\t\t\t\t\tstyle=\"background-color: #F0FFFF;\">\r\n");
            out.write("\t\t\t\t\t<thead>\r\n");
            out.write("\t\t<tr class=\"success\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<th ><b>SNo</b></th> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 200px;\"><b>PIU Name</b></th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 100px;\" ><b>Auto Mail Action</b></th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 150px;\" ><b>Real Time Date Setting</b></th>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</tr></thead>\r\n");
            out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t");

								while (rs.next()) {
									 piu_name= rs.getString(1);
						        	 mailStatus= rs.getString(2);
						        	 rdStatus= rs.getString(3);
						        	 
							if(mailStatus.equalsIgnoreCase("1")){
								Action="On";
							}else{
								Action="Off";
							}
							if(rdStatus.equalsIgnoreCase("1")){
								Setting="On";
							}else{
								Setting="Off";
							}
							
									
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr class=\"active\">\r\n");
            out.write("\t\t\t<td>");
            out.print(count);
            out.write("</td>\r\n");
            out.write("\t\t\t<td>");
            out.print(piu_name);
            out.write("</td>\r\n");
            out.write("\t\t\t");
if(Action.equalsIgnoreCase("On")) {
			
            out.write("\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t<td style=\"color:green; font-weight: bold;\">");
            out.print(Action);
            out.write("</td>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t");
}else{
				
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<td style=\"color:red;text-decoration:underline;\">");
            out.print(Action);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t");
	
			}
			if(Setting.equalsIgnoreCase("On")) {
				
            out.write("\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t<td style=\"color:green;font-weight: bold;\">");
            out.print(Setting);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t");
}else{
					
            out.write("\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<td style=\"color:red;text-decoration:underline;\">");
            out.print(Setting);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t");
	
				}
			
			count++;}
		} catch(Exception e){
			
			e.printStackTrace();
		}  finally {
			    try { rs44.close(); } catch (Exception e) { /* ignored */ }
			    try { stmt3.close(); } catch (Exception e) { /* ignored */ }
			    try { rs33.close(); } catch (Exception e) { /* ignored */ }
			    try { stmt2.close(); } catch (Exception e) { /* ignored */ }
			    try { rs22.close(); } catch (Exception e) { /* ignored */ }
			    try { stmt1.close(); } catch (Exception e) { /* ignored */ }
			    try { rs.close(); } catch (Exception e) { /* ignored */ }
			    try { stmt.close(); } catch (Exception e) { /* ignored */ }
			    try { conn.close(); } catch (Exception e) { /* ignored */ }
			}
		
							//	conn.close();
   //    }
 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\r\n");
            out.write("\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"dialogid4\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure you want to select Document Action Alert Setting as 'on'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"doc_action_alert('on');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid4').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"dialogid41\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure You want to select Document Action Alert Setting as 'off'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"doc_action_alert('off');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid41').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dialogid3\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure you want to select User Profile Change Alert Setting as 'on'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"prof_alert('on');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid3').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"dialogid31\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure You want to select User Profile Change Alert Setting as 'off'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"prof_alert('off');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid31').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dialogid\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure you want to select Real Time Date Setting as 'on'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"realdateset('on');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"dialogid1\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure You want to select Real Time Date Setting as 'off'<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"realdateset('off');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid1').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t<div id=\"dialogid28\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure you want to select Manual Alert/reminder Setting as 'on' for this PIU<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"manualalertset('on');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid28').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"dialogid128\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Are you Sure you want to select Manual Alert/reminder Setting as 'off' for this PIU<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" class=\"btn btn-primary\" onclick=\"manualalertset('off');\">ok</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" onclick=\"$('#dialogid128').dialog('close');\">cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t<div id=\"dialogid55\" style=\"display: none\"\r\n");
      out.write("\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br> Wrong Password !!!!  .. retry .....<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button id=\"appok\" type=\"button\" class=\"btn btn-primary\" onclick=\"location.reload();\">Yes</button>\r\n");
      out.write("         <button id=\"appcancle\" class=\"btn btn-primary\" type=\"button\" onclick=\"$('#dialogid55').dialog('close'); location.href='NewIndex.jsp';\">No</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /Admin/datesetting.jsp(420,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.Project_stage != null) and (param.MyProject_stage != null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");

							//System.out.println("112334");
							String sql3=null;
							Connection conn = null;
							String username = (String) session.getAttribute("user_name");
							String str=request.getParameter("Project_stage");
							System.out.println("33333334"+str);
							if (str.equalsIgnoreCase("third") ) {
								String prof_alert2 = request.getParameter("profilealertoption");
								System.out.println("112334"+prof_alert2);
								try {
									Context initCtx = new InitialContext();
									Context envCtx = (Context) initCtx.lookup("java:comp/env");
									DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
									
										
									conn = ds.getConnection();
									if(prof_alert2.equalsIgnoreCase("off")){
									 sql3 = "update xx_maintenance set Description='Off' where Item='profile_alert'";
									}
									else{
										sql3 = "update xx_maintenance set Description='On' where Item='profile_alert'";
									}
									PreparedStatement ps1 = conn.prepareStatement(sql3);
									ps1.executeUpdate();
								}
								catch(Exception e){
									e.printStackTrace();
									
								} finally {
	    						    try { conn.close(); } catch (Exception e) { /* ignored */ }
	    						}
								
							 
							
							
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 112px 0px 0px 0px;\">\r\n");
            out.write("\t\t\t\t<strong>Success!</strong> User Profile Change Alert Setting Changed Successfully ..... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='admn_logout.jsp'\">Please log out for working with changed setting !</button> \r\n");
            out.write("\t\t\t\t\t</div>\t\r\n");
            out.write("\t\t\t\t\t");

					} else if (str.equalsIgnoreCase("fourth") ) {
						String doc_action_alert2 = request.getParameter("docactionalertoption");
						//System.out.println("112334"+prof_alert2);
						try {
							Context initCtx = new InitialContext();
							Context envCtx = (Context) initCtx.lookup("java:comp/env");
							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
							
								
							conn = ds.getConnection();
							if(doc_action_alert2.equalsIgnoreCase("off")){
							 sql3 = "update xx_maintenance set Description='Off' where Item='doc_action_alert'";
							}
							else{
								sql3 = "update xx_maintenance set Description='On' where Item='doc_action_alert'";
							}
							PreparedStatement ps1 = conn.prepareStatement(sql3);
							ps1.executeUpdate();
						}
						catch(Exception e){
							e.printStackTrace();
							
						} finally {
						    try { conn.close(); } catch (Exception e) { /* ignored */ }
						}
						
					 
					
					
            out.write("\r\n");
            out.write("\t\t\t\t\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 112px 0px 0px 0px;\">\r\n");
            out.write("\t\t<strong>Success!</strong> Document Action Alert Setting Changed Successfully ..... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='admn_logout.jsp'\">Please log out for working with changed setting !</button> \r\n");
            out.write("\t\t\t</div>\t\r\n");
            out.write("\t\t\t");

			} else if (str.equalsIgnoreCase("first")) {
						String realdateoption =request.getParameter("realdateoption");			
								try {
									Context initCtx = new InitialContext();
									Context envCtx = (Context) initCtx.lookup("java:comp/env");
									DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
									
										
									conn = ds.getConnection();
									if(realdateoption.equalsIgnoreCase("off")){
									 sql3 = "update xx_user_master set RealdateStatus='0'";
									 //session.setAttribute("RealdateStatus","0");
									}
									else{
										 sql3 = "update xx_user_master set RealdateStatus='1'";	
										// session.setAttribute("RealdateStatus","1");
									}
									PreparedStatement ps1 = conn.prepareStatement(sql3);
									ps1.executeUpdate();
								}
								catch(Exception e){
									e.printStackTrace();
									
								} finally {
	    						    try { conn.close(); } catch (Exception e) { /* ignored */ }
	    						}
								
							 
							
							
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 112px 0px 0px 0px;\">\r\n");
            out.write("\t\t\t\t<strong>Success!</strong> Date Setting Changed Successfully ..... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='admn_logout.jsp'\">Please log out for working with changed Date setting !</button> \r\n");
            out.write("\t\t\t\t\t</div>\t\r\n");
            out.write("\t\t\t\t\t");

			} else if (str.equalsIgnoreCase("fifth")) {
				int updateQuery = 0;
				int updateQuery2 = 0;
				PreparedStatement p1 =null, p2=null;
				try {
					Context initCtx = new InitialContext();
					Context envCtx = (Context) initCtx.lookup("java:comp/env");
					DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
					
						
					conn = ds.getConnection();
				
					String sql1="DELETE x FROM xx_approval_workflow   x "+
							  " join (select count(*),max(rownum) as maxrow, Document_id, Added_ByUser, Assigned_To, Action, Level, AssignedDays "+
							  " from xx_approval_workflow group by Document_id, Added_ByUser, Assigned_To, Action, Level, AssignedDays "+
							  " having count(*) > 1) y on x.rownum=y.maxrow";
					p1 = conn.prepareStatement(sql1);
                   updateQuery = p1.executeUpdate();
                while (updateQuery != 0) {
                	updateQuery = p1.executeUpdate();
                }
                String sql2="DELETE x FROM xx_record_actions  x "+
                		 " join (SELECT COUNT(*), max(rownum) as maxrow, Document_id, CurrentDate, ActionPerformed, ActionPerformedBy, Information, ActionedOn, AssignedDays "+ 
                		" FROM xx_record_actions GROUP BY Document_id, CurrentDate, ActionPerformed, ActionPerformedBy, Information, ActionedOn, AssignedDays "+
                		" HAVING COUNT(*)>1) y on x.rownum=y.maxrow";

				p2 = conn.prepareStatement(sql2);
             updateQuery2 = p2.executeUpdate();
          while (updateQuery2 != 0) {
          	updateQuery2 = p2.executeUpdate();
          }
					
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            if (_jspx_meth_sql_005fupdate_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t");
            if (_jspx_meth_sql_005fupdate_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
              return;
            out.write('\r');
            out.write('\n');
            out.write('	');

					} catch(Exception e){
									e.printStackTrace();
									
								} finally {
	    						    try { conn.close(); } catch (Exception e) { /* ignored */ }
	    						}
            out.write("\r\n");
            out.write("\t    \t\t\t\t\t\t\r\n");
            out.write("\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 112px 0px 0px 0px;\">\r\n");
            out.write("\t\t<strong>Success!</strong> Duplicate document records deleted........ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='NewIndex.jsp';\">Please go to home page !</button> \r\n");
            out.write("\t\t\t</div>\t\r\n");
            out.write("\t\t\t");

					} else if (str.equalsIgnoreCase("second")) {
					String piu_id =request.getParameter("alertPIU");
					String manualalertoption =request.getParameter("manualalertoption");
					
					try {
						Context initCtx = new InitialContext();
						Context envCtx = (Context) initCtx.lookup("java:comp/env");
						DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
											
						conn = ds.getConnection();
						
				if(manualalertoption.equalsIgnoreCase("off")){
							 sql3 = "update xx_user_master set MailStatus='0' where PIU_Id="+piu_id;
							 //session.setAttribute("RealdateStatus","0");
							}
							else{
								 sql3 = "update xx_user_master set MailStatus='1' where PIU_Id="+piu_id;	
								// session.setAttribute("RealdateStatus","1");
							}
							PreparedStatement ps2 = conn.prepareStatement(sql3);
							ps2.executeUpdate();
				
					}
					catch(Exception e){
						e.printStackTrace();
						
					} finally {
					    try { conn.close(); } catch (Exception e) { /* ignored */ }
					}
					
				 
				
				
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"alert alert-success\" align=\"center\" style=\"margin: 112px 0px 0px 0px;\">\r\n");
            out.write("\t<strong>Success!</strong> Alerts/Reminders Setting Changed Successfully ..... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \r\n");
            out.write("\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='datesetting.jsp'\">OK</button> \r\n");
            out.write("\t\t</div>\t\r\n");
            out.write("\t\t");

		} 
							
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\t      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,700');\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tmargin-top:150px;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<footer>\r\n");
      out.write("<div class=\"city\">\r\n");
      out.write("  <ul class=\" nav navbar-nav\">\r\n");
      out.write("  \r\n");
      out.write("    <li class=\"footerli\">Rail Vikas Nigam Limited.</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul   class=\"nav navabar-nav\" style=\"float:right;\">\r\n");
      out.write("   <li class=\"footerli\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Design & Developed By<a href=\"http://www.awcsoftware.net\" style=\"text-decoration:none;\">AWC SOFTWARE PVT LTD</a></li>\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</footer> -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer-basic-centered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\" style=\"float:left;\">Rail Vikas Nigam Limited</p>\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\" style=\"float:center; font-family:serif; font-size:14px; font-style:italic; margin-top:5px;\">Ver:2.30.pks</p>\r\n");
      out.write("\t\t\t<p class=\"footer-company-name\" style=\"float:right; margin-top:-20px;\"> Design & Developed By<a href=\"http://www.awcsoftware.net\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AWC SOFTWARE PVT LTD</a></p>\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Admin/datesetting.jsp(155,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.Project_stage == null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\r\n");
          out.write("\t\r\n");
          out.write("\t<div id=\"mypass\" align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<br> <br>Special Password: <input type=\"password\" id=\"mypass1\" name=\"mypass1\"  style=\"margin-left: 30px; width:150px; background-color:yellow;\"/><br><br>\r\n");
          out.write("\t\t\t\t\t\t\t\t<br><br>\r\n");
          out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\t<button id=\"appok1\" type=\"button\" class=\"btn btn-primary\" onclick=\"mypasstest();\">OK</button>\r\n");
          out.write("    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    <button id=\"appcancle\" type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='NewIndex.jsp';\">Cancel</button>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sql_005fupdate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:update
    org.apache.taglibs.standard.tag.rt.sql.UpdateTag _jspx_th_sql_005fupdate_005f0 = (org.apache.taglibs.standard.tag.rt.sql.UpdateTag) _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.UpdateTag.class);
    boolean _jspx_th_sql_005fupdate_005f0_reused = false;
    try {
      _jspx_th_sql_005fupdate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fupdate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /Admin/datesetting.jsp(563,5) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fupdate_005f0.setDataSource("jdbc/MySQLDB");
      // /Admin/datesetting.jsp(563,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fupdate_005f0.setVar("rs");
      int[] _jspx_push_body_count_sql_005fupdate_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_sql_005fupdate_005f0 = _jspx_th_sql_005fupdate_005f0.doStartTag();
        if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_sql_005fupdate_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fupdate_005f0);
          }
          do {
            out.write("\r\n");
            out.write("\t\t\tDELETE x FROM xx_record_actions x where x.ActionPerformedBy='null'\r\n");
            out.write("\t\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_sql_005fupdate_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_sql_005fupdate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_sql_005fupdate_005f0[0]--;
          }
        }
        if (_jspx_th_sql_005fupdate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sql_005fupdate_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sql_005fupdate_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sql_005fupdate_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fupdate_005f0);
      _jspx_th_sql_005fupdate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fupdate_005f0, _jsp_getInstanceManager(), _jspx_th_sql_005fupdate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sql_005fupdate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sql:update
    org.apache.taglibs.standard.tag.rt.sql.UpdateTag _jspx_th_sql_005fupdate_005f1 = (org.apache.taglibs.standard.tag.rt.sql.UpdateTag) _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.get(org.apache.taglibs.standard.tag.rt.sql.UpdateTag.class);
    boolean _jspx_th_sql_005fupdate_005f1_reused = false;
    try {
      _jspx_th_sql_005fupdate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sql_005fupdate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /Admin/datesetting.jsp(568,2) name = dataSource type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fupdate_005f1.setDataSource("jdbc/MySQLDB");
      // /Admin/datesetting.jsp(568,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sql_005fupdate_005f1.setVar("rs");
      int[] _jspx_push_body_count_sql_005fupdate_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_sql_005fupdate_005f1 = _jspx_th_sql_005fupdate_005f1.doStartTag();
        if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_sql_005fupdate_005f1[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_sql_005fupdate_005f1);
          }
          do {
            out.write("\r\n");
            out.write("\t\tDELETE x FROM xx_document_mapping  x JOIN  xx_document_mapping  t ON  x.document_number= t.document_number and x.Document_Name= t.Document_Name and  x.Document_Type= t.Document_Type and x.Submitted_by= t.Submitted_by  and x.Project_ID= t.Project_ID and x.package_ID = t.package_ID  AND t.Document_Map_Id < x.Document_Map_Id\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_sql_005fupdate_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_sql_005fupdate_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_sql_005fupdate_005f1[0]--;
          }
        }
        if (_jspx_th_sql_005fupdate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_sql_005fupdate_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_sql_005fupdate_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_sql_005fupdate_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fsql_005fupdate_0026_005fvar_005fdataSource.reuse(_jspx_th_sql_005fupdate_005f1);
      _jspx_th_sql_005fupdate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sql_005fupdate_005f1, _jsp_getInstanceManager(), _jspx_th_sql_005fupdate_005f1_reused);
    }
    return false;
  }
}
