/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.86
 * Generated at: 2018-10-30 06:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.itextpdf.text.log.SysoLogger;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import java.util.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import java.net.URLEncoder;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;

public final class FinallyApprovedShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Admin/included/NewHeader.jsp", Long.valueOf(1538119203935L));
    _jspx_dependants.put("/WEB-INF/sessionCheck1.jspf", Long.valueOf(1524567358000L));
    _jspx_dependants.put("/Admin/sessionCheck.jsp", Long.valueOf(1524567356000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
int timeout = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout + "; URL = admn_login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 

int timeout1 = session.getMaxInactiveInterval();
response.setHeader("Refresh", timeout1 + "; URL = admn_login.jsp");

if(((String)session.getAttribute("user_name"))==null)
       {
           
	response.sendRedirect("admn_login.jsp");
           
       }
      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

 String theme3 = (String) pageContext.getAttribute("myTheme", PageContext.SESSION_SCOPE);
if (theme3!=null) {
if (theme3.equalsIgnoreCase("brown") ) { 
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
 } else if (theme3.equalsIgnoreCase("blue")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBlue.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("green")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmGreen.css\">\r\n");
      out.write("\t\t");
} else if (theme3.equalsIgnoreCase("magenta")) { 
      out.write(" \r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/Thmmagenta.css\">\r\n");
      out.write("\t\t");
}
} else {
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/ThmBrown.css\">\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>PDAMS</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".white-marquee {\r\n");
      out.write("   font-family:   arial, serif, \"Times New Roman\", calibri, Times;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor:  white;\r\n");
      out.write("\t//margin-left:50px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tpadding-bottom:5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>   \r\n");

//String mailstatus=(String)session.getAttribute("MailStatus"); 
//String user = (String) session.getAttribute("user_name");
String user_code = (String) session.getAttribute("User_Code");
if (user_code!=null) {} else {user_code="0";}
 String mq=null, mqLaunch=null, mqMaint=null, mqOther=null, mqRly=null, mqRVNL=null;					
 //System.out.println("code="+user_code);	
  Connection conn7 = null;                                                      
     			PreparedStatement ps777=null;
     			ResultSet  rs777=null;
     						//Statement stmt7 = null;
     						try {
     							Context initCtx = new InitialContext();
     							Context envCtx = (Context) initCtx.lookup("java:comp/env");
     							DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");

     							conn7 = ds.getConnection();
     							String sql35 = "select item, description from xx_maintenance";
     									
    								ps777 = conn7.prepareStatement(sql35);
    								rs777 = ps777.executeQuery();
    								while (rs777.next()) {
    									String item=rs777.getString(1);
    									 String desc=rs777.getString(2);
    									if (item.equalsIgnoreCase("marquee-launch")) {
    										mqLaunch=desc;
    									} else if (item.equalsIgnoreCase("marquee-maint")) {
    										mqMaint=desc;
    									} else if (item.equalsIgnoreCase("marquee-other")) {
    										mqOther=desc;
    									} else if (item.equalsIgnoreCase("marquee-Rly")) {
    										mqRly=desc;
    									} else if (item.equalsIgnoreCase("marquee-RVNL")) {
    										mqRVNL=desc;
    									} 
    								}
    								if (user_code.equalsIgnoreCase("2")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRly;
    								} else if (user_code.equalsIgnoreCase("5")) {
    									mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqRVNL;
    								} else {
    								mq= mqLaunch+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqMaint+"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"+mqOther;
    								}		 
    				    				//System.out.println("marquee="+mq);
     						}catch(Exception e){
    							
    							e.printStackTrace();
    						} finally {
    						    try { rs777.close(); } catch (Exception e) { /* ignored */ }
    						    try { ps777.close(); } catch (Exception e) { /* ignored */ }
    						    try { conn7.close(); } catch (Exception e) { /* ignored */ }
    						}



      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"menu1\" value='");
      out.print(session.getAttribute("user_name") );
      out.write("'>\r\n");
      out.write("     \t   <div class=\"header\">\r\n");
      out.write("   \r\n");
      out.write(" \t\t   <table width=\"100%\"><tr><th width=15%>\r\n");
      out.write("    \t\t  <img src=\"images/Rail_logo.png\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write("    \t\t  \r\n");
      out.write("   </td>\r\n");
      out.write("   <th width=60%>\r\n");
      out.write("      \t\t <h2 style=\" margin-left:5px;\"><i>Project Documents Approval Monitoring System (PDAMS)</i></h2>\t\r\n");
      out.write("   \r\n");
      out.write("   </th><th width=25%>\r\n");
      out.write("\t  <img src=\"images/RVNL_LOGO.jpg\"  class=\"img-responsive\" style=\"float:left;height:80px;margin-left:10px;\">\r\n");
      out.write(" \t\t  </table>\t\r\n");
      out.write("   </div>\r\n");
      out.write("\t   <div class=\"topmenu\" id=\"menu\">\r\n");
      out.write("\t  <div id=\"menu1\"  style=\"float:left;\"> \r\n");
      out.write("\t  \t\t<ul>\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t\t<!-- <li><a href=\"user_index.jsp\">Add/Modify Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"user_Project.jsp\">My Projects</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"Reportpiuinitiate.jsp\">My Reports</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"MoreInfo.jsp\">Returned Tasks</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"PullBack.jsp\">PullBack Doc</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinalApproval.jsp\">Docs under Approval</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"FinallyApprovedShow.jsp\">Approved Docs</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"ManualMail.jsp\">Reminders</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"User_List.jsp\">User List</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"changepasswordlocaladmin.jsp\">Change Password</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"helpmain.jsp\">Help</a></li>\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"admn_logout.jsp\">Logout</a></li>  -->\r\n");
      out.write("\t   \t\t\t\t\t<li><a href=\"NewIndex.jsp\">Home</a></li>\r\n");
      out.write("\t   \t\t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t</ul>\t \r\n");
      out.write("\t   \t\t\t\t\t</div>  \r\n");
      out.write("\t   \t\t\t\t\t");

	   					if (!mq.equalsIgnoreCase("") && mq!=null) {
	   					
      out.write("\t\r\n");
      out.write("\t   \t<div id=\"menu11\" ></div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t   <div id=\"menu2\"  style=\"width:70%; float:left;\">     \t\t\t\t\t\r\n");
      out.write("\t   <marquee><span class=\"white-marquee\" id=\"white-marquee\" style=\"float:right; width:100%\">");
      out.print(mq );
      out.write("</span></marquee>  </div>\r\n");
      out.write("\t  ");

	  	}
	   	
      out.write("\t\r\n");
      out.write("\t   \t\r\n");
      out.write("\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link href=\"resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"resources/bootstrap/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"resources/JS/UserIndex.js\"></script>\r\n");
      out.write("<script src=\"resources/JS/validateSysAdmin230.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"resources/JS/Approval_wf230.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/JS/datasort.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".ui-datepicker-year {\r\n");
      out.write("   background-color: #cc0000;\r\n");
      out.write(" padding-left:20px;\r\n");
      out.write("}\r\n");
      out.write("#example_length {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("#example {\r\n");
      out.write("    width: inherit;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("div.absolute {\r\n");
      out.write("   \tposition:absolute;\r\n");
      out.write("   \tmargin-top: 5px;\r\n");
      out.write("   \tmargin-left: 13px;\r\n");
      out.write("   \tmargin-bottom: 20px;\r\n");
      out.write(" \tpadding: 15 px;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    border: 3px double #ff4d4d;\r\n");
      out.write("    background-color:#ffe6e6;\r\n");
      out.write("        }\r\n");
      out.write("    table.center {\r\n");
      out.write("    margin-left:auto; \r\n");
      out.write("    margin-right:auto;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function Showinrept(document_id,PrintOpt) {\r\n");
      out.write("\t//alert(\"you are bold......\"+document_id+\"print choice=\"+PrintOpt);\r\n");
      out.write("\t\t\tdocument.final_approve.stage.value=\"first\";\r\n");
      out.write("\t\t\tdocument.final_approve.doc_id.value=document_id;\r\n");
      out.write("\t\t\t//document.final_approve.user_id.value=user_id;\r\n");
      out.write("\t\t\t//alert(user_id);\r\n");
      out.write("\t\t\tif (PrintOpt==\"Y\") {\r\n");
      out.write("\t\t\t\tdocument.final_approve.showinreport1.value=\"N\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.final_approve.showinreport1.value=\"Y\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"final_approve\").submit();\r\n");
      out.write("\t\t\talert(\"Show in Report status for document Id=\"+docid+\" changed....\");\r\n");
      out.write("\t}\r\n");
      out.write("function frezedate(id, startDate) {\r\n");
      out.write("\t\tjQuery.noConflict();\r\n");
      out.write("\r\n");
      out.write("\t\tvar idof = id;\r\n");
      out.write("\t\t//alert(startDate);\r\n");
      out.write("\t\tvar chunks = startDate.split('/');\r\n");
      out.write("\t\tvar formattedDate = [ chunks[1], chunks[0], chunks[2] ].join(\"/\");\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#\" + idof).datepicker({\r\n");
      out.write("\r\n");
      out.write("\t\t\tdateFormat : 'dd/mm/yy',\r\n");
      out.write("\t\t\tminDate : formattedDate,\r\n");
      out.write("\t\t\tmaxDate : '0', changeYear: true\r\n");
      out.write("\r\n");
      out.write("\t\t}).datepicker(\"show\").val();\r\n");
      out.write("\t\t//var today = new Date(); var dd = today.getDate(); \r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar people, asc1 = 1, asc2 = 1, asc3 = 1, asc4 = 1, asc5 = 1, asc6 = 1, asc7 = 1, asc8 = 1;\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tpeople = document.getElementById(\"people\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction sort_table(tbody, col, asc) {\r\n");
      out.write("\t\tvar rows = tbody.rows, rlen = rows.length, arr = new Array(), i, j, cells, clen;\r\n");
      out.write("\t\t// fill the array with values from the table\r\n");
      out.write("\t\tfor (i = 0; i < rlen; i++) {\r\n");
      out.write("\t\t\tcells = rows[i].cells;\r\n");
      out.write("\t\t\tclen = cells.length;\r\n");
      out.write("\t\t\tarr[i] = new Array();\r\n");
      out.write("\t\t\tfor (j = 0; j < clen; j++) {\r\n");
      out.write("\t\t\t\tarr[i][j] = cells[j].innerHTML;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// sort the array by the specified column number (col) and order (asc)\r\n");
      out.write("\t\tarr.sort(function(a, b) {\r\n");
      out.write("\t\t\treturn (a[col] == b[col]) ? 0\r\n");
      out.write("\t\t\t\t\t: ((a[col] > b[col]) ? asc : -1 * asc);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// replace existing rows with new rows created from the sorted array\r\n");
      out.write("\t\tfor (i = 0; i < rlen; i++) {\r\n");
      out.write("\t\t\trows[i].innerHTML = \"<td>\" + arr[i].join(\"</td><td>\") + \"</td>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tjQuery.extend( jQuery.fn.dataTableExt.oSort, {\r\n");
      out.write("\t\t    \"date-uk-pre\": function ( a ) {\r\n");
      out.write("\t\t        if (a == null || a == \"\") {\r\n");
      out.write("\t\t            return 0;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        var ukDatea = a.split('-');\r\n");
      out.write("\t\t        return (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t    \"date-uk-asc\": function ( a, b ) {\r\n");
      out.write("\t\t        return ((a < b) ? -1 : ((a > b) ? 1 : 0));\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t    \"date-uk-desc\": function ( a, b ) {\r\n");
      out.write("\t\t        return ((a < b) ? 1 : ((a > b) ? -1 : 0));\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t} );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t    $('#example').DataTable( {\r\n");
      out.write("\t        columnDefs: [ {  type: 'date-uk', targets: [6,7]}, {\r\n");
      out.write("\t            targets: [ 0 ],\r\n");
      out.write("\t            orderData: [ 0, 1 ]\r\n");
      out.write("\t        }, {\r\n");
      out.write("\t            targets: [ 1 ],\r\n");
      out.write("\t            orderData: [ 1, 0 ]\r\n");
      out.write("\t        }, {\r\n");
      out.write("\t            targets: [ 4 ],\r\n");
      out.write("\t            orderData: [ 4, 0 ]\r\n");
      out.write("\t        } ],\r\n");
      out.write("  \t\t\t\"infoCallback\": function( settings, start, end, max, total, pre ) {\r\n");
      out.write("\t\t\t\tif (max==total) { return \"Showing \" + (end-start+1) + \"  of \" +total+\" records\"}\r\n");
      out.write("\t\t\t\telse {return \"Showing \" + (end-start+1) + \"  of \" +total+\" records (filtered from total \" + max+\" records)\"}\r\n");
      out.write("\t\t\t   \t}\r\n");
      out.write("\t    } );\r\n");
      out.write("\t} );\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<title>Final Approval</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <div><h4 style='width: 400px; margin-left: 27px'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Documents Under Approval</h4></div>\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"absolute\" style=\"font-weight:bold\" ><h8>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Approved Documents] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h8>\r\n");
      out.write("\r\n");
      out.write("<h8><font style=\"color:red; font-weight:normal\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome&nbsp;</font><font style=\"color:#3333cc; font-weight:normal\">:&nbsp;");
      out.print((String)session.getAttribute("user_name") );
      out.write("&nbsp;&nbsp;&nbsp;</font></h8>\r\n");
      out.write("</div><br>\t\r\n");
      out.write("\t");

		response.setHeader("Cache-control", "no-store");
		response.setHeader("Pragma", "no-cache");
		response.setDateHeader("Expires", -1);
		session.removeAttribute("backurl");
		String user1 = (String) session.getAttribute("user_name");
		
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		Date submittedDate;
		String stage1 = request.getParameter("stage");
		String userid1 = request.getParameter("user_id");
		String docid = request.getParameter("doc_id");
		String show1 = request.getParameter("showinreport1");
		
	
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"final_approve\" name=\"final_approve\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"stage\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\tname=\"doc_id\"> <input type=\"hidden\" name=\"user_id\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"approvaldate\">\t\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"showinreport1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /Admin/FinallyApprovedShow.jsp(223,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.stage == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t<br>\r\n");
            out.write("\t\t\t<div class='scrollit' style='overflow-x: scroll;width: 100%;position:relative;'>\r\n");
            out.write("\t\t\t<table class=\"table table-hover table-bordered\"\r\n");
            out.write("\t\t\t\tstyle=\"background-color: #F0FFFF\" id=\"example\" class=\"display\" border=\"1\">\r\n");
            out.write("\t\t\t\t<thead>\r\n");
            out.write("\t\t\t\t\t<tr class=\"success\">\r\n");
            out.write("\t\t\t\t\t\t<th><b>SNo</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Project Name</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Package Name</b></th>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<th><b>Document Type</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Document\tNo.</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Document Name</b></th>\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<th><b>Submitted date</b></th>\r\n");
            out.write("\t\t\t\t\t\t\t \r\n");
            out.write("\t\t\t\t\t\t\t \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<th><b>Approval Date</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Log Details</b></th>\r\n");
            out.write("\t\t\t\t\t\t<th><b>Show in Report</b></th>\r\n");
            out.write("\t\t\t\t</thead>\r\n");
            out.write("\t\t\t\t<tbody id=\"people\">\r\n");
            out.write("\t\t\t\t\t");

					Connection conn = null;
					ResultSet rsm=null;
					Date frezedate=null;
					String frezestr=null;
                    		int count=1;	

							try {
								
								Context initCtx = new InitialContext();
								Context envCtx = (Context) initCtx.lookup("java:comp/env");
								DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
								String userid = null;

								conn = ds.getConnection();
								String sql3 = "select User_ID from xx_user_master where User_name='"
										+ user1 + "'";
								PreparedStatement ps1 = conn.prepareStatement(sql3);
								ResultSet rs1 = ps1.executeQuery();

								if (rs1.next()) {
									userid = rs1.getString("User_ID");
									
								}
							
							
								
								String  documentno = null, documentname = null, documentType = null, project_idd = null, piu_id = null, project_id = null, document_id = null;
								Date submitiondate = null;
								String submitedbyq = "select * from xx_document_mapping where Submitted_by='"
										+ userid
										+ "' and Forwarded='yes' and Document_Status='Finally Approved' ORDER BY Date_of_Submission";

								PreparedStatement ps2 = conn.prepareStatement(submitedbyq);
								ResultSet rs2 = ps2.executeQuery();

								while (rs2.next()) {
									documentname = rs2.getString("Document_Name");
									documentno = rs2.getString("Document_Number");
									String documentType12 = rs2.getString("Document_Type");
									documentType = URLEncoder.encode(documentType12, "UTF-8");
									document_id = rs2.getString("Document_Map_ID");
									
									project_idd = rs2.getString("Project_ID");
									
									submittedDate = rs2.getDate("Date_of_Submission");
									String sD = "-";
									
									sD = new SimpleDateFormat("dd-MM-yyyy")
											.format(submittedDate);
									
									
									
									String sql12="select * from xx_record_actions where Document_id='"+document_id+"'";
									PreparedStatement psdat = conn.prepareStatement(sql12);
									ResultSet rsdat = psdat.executeQuery();
									while(rsdat.next()){
										frezedate=rsdat.getDate("Actionedon");
										
									}
									String Package_name=null;
									String sql112="select * from xx_packages_project where project_id='"+project_idd+"'";
									PreparedStatement psdat1 = conn.prepareStatement(sql112);
									ResultSet rsdat1 = psdat1.executeQuery();
									while(rsdat1.next()){
										
										 Package_name=rsdat1.getString("Package_name");										
									}
									
									frezestr = new SimpleDateFormat("dd-MM-yyyy")
									.format(frezedate);	
									String piuq = "select PIU_of_RVNL,Project from xx_projectattributes_master where project_id='"
											+ project_idd + "'";

									PreparedStatement ps3 = conn.prepareStatement(piuq);
									ResultSet rs3 = ps3.executeQuery();
									while (rs3.next()) {

										piu_id = rs3.getString("PIU_of_RVNL");
										project_id = rs3.getString("Project");

										
					
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t<td>");
            out.print(count);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.print(project_id);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.print(Package_name );
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.print(documentType12);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.print(documentno);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td>");
            out.print(documentname);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.print(sD);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.print(frezestr);
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<td><a href=\"recordReport.jsp?Document_Type=");
            out.print(documentType);
            out.write("&doc_id=");
            out.print(document_id);
            out.write("\" target=\"_blank\">\r\n");
            out.write("\t\t\t\t\tLog Details </a></td>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("<td> <select name=\"ShowInReport\" id=\"ShowInReport\" style=\"width: 205px\" onchange=\"Showinrept('");
            out.print(document_id);
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.print(rs2.getString("ShowInReport") );
            out.write("')\">\t\t\t\t\t \r\n");
            out.write(" ");
  if(rs2.getString("ShowInReport").equalsIgnoreCase("y")){ 
            out.write("\r\n");
            out.write(" <option selected=\"");
            out.print(rs2.getString("ShowInReport") );
            out.write('"');
            out.write('>');
            out.print(rs2.getString("ShowInReport") );
            out.write("</option>\r\n");
            out.write(" \r\n");
            out.write("\t\t\t\t\t\t<!-- <option value=\"Y\">Y</option> -->\r\n");
            out.write("\t\t\t\t\t\t<option value=\"N\">N</option>  \r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t");
}
 else {
            out.write("\r\n");
            out.write("  <option selected=\"");
            out.print(rs2.getString("ShowInReport") );
            out.write('"');
            out.write('>');
            out.print(rs2.getString("ShowInReport") );
            out.write("</option>\r\n");
            out.write(" \r\n");
            out.write("\t\t\t\t\t\t<!-- <option value=\"Y\">Y</option> -->\r\n");
            out.write("\t\t\t\t\t\t<option value=\"Y\">Y</option>  \r\n");
            out.write("\t\t\t\t\t\t");
} 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t</select></td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t</tr>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t");

						
						}
								
								count++;	
								}
																	
					
            out.write("\r\n");
            out.write("\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t</table>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t\t");

				conn.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
			
            out.write("\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /Admin/FinallyApprovedShow.jsp(385,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.stage != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\r\n");
            out.write("\t\t\t");

				Connection conn = null;
					String username = (String) session.getAttribute("user_name");
					try {
						Context initCtx = new InitialContext();
						Context envCtx = (Context) initCtx.lookup("java:comp/env");
						DataSource ds = (DataSource) envCtx.lookup("jdbc/MySQLDB");
						
						conn = ds.getConnection();
						String sql3 = "update xx_document_mapping set ShowInReport='" + show1 + "' where Document_Map_ID='"
								+ docid + "'";
						PreparedStatement ps1 = conn.prepareStatement(sql3);
						ps1.executeUpdate();
											
					conn.close();
					} catch (Exception e) {
						e.printStackTrace();

					}
					response.sendRedirect("FinallyApprovedShow.jsp");
			
            out.write("\r\n");
            out.write("\t\t\t<!--   <div class=\"alert alert-success\" align=\"center\">\r\n");
            out.write("\t\t\t\t<strong>Success!</strong> Document Printing Status has been changed to\r\n");
            out.write("\t\t\t\t");
            out.print(username );
            out.write(".\r\n");
            out.write("\t\t\t\t</div> -->\r\n");
            out.write("\t\t\t\r\n");
            out.write("\r\n");
            out.write("\t\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
